### ISSUE TITLE
Close buffer with rightclick

### ISSUE THREAD

**Issue by astier** [akinsho/nvim-bufferline.lua#10]
I think it would be great if it would be possible to close a buffer by clicking on it with the right mouse-button. This would have the following benefits:

- Safe space by removing the close-symbol
- Less visual clutter/noise
- Closing buffer becomes easier because you dont have to click exactly on the small area of the close-symbol

**Comment by akinsho** [comment]
I think using the right mouse to close the buffer would be an interesting addition. I've added that functionality to the dev branch. Give it a try and see if it works for you 👍🏿

**Comment by astier** [comment]
It works for me! Thank you for the quick response. The only problem I have now is that I can not disable the close-icon. Here is my minimal vimrc:

```vim
set runtimepath+=~/.local/share/nvim/plugins/nvim-bufferline.lua/
lua << EOF
require'bufferline'.setup{
    options = {
        show_buffer_close_icon = "false",
    }
}
EOF
```

It still shows the close-icon besides the buffers.

**Comment by astier** [comment]
Another issue I encountered is that if I have a file-explorer like chadtree open and I right click to close the currently opened buffer the window also closes and I am left with the file-explorer. I modified my own mappings to close buffers such that the current window is preserved in a split that I completely forgot that this is vims default behavior. How are you dealing with it?

**Comment by akinsho** [comment]
@astier the example you posted of trying to turn off the icons is using a string rather than a boolean. Try removing the quotes around false.

Regarding closing buffers tbh that's an issue with deleting buffers and vim. You can add a hook to your preferred tree that is it's the only window remaining then execute a buffer delete on the tree window

**Comment by astier** [comment]
> the example you posted of trying to turn off the icons is using a string rather than a boolean

haha true. It still doesnt work however:

```vim
set runtimepath+=~/.local/share/nvim/plugins/nvim-bufferline.lua/
lua << EOF
require'bufferline'.setup{
    options = {
        show_buffer_close_icon = false,
    }
}
EOF
```

Does it work for you with my minimal vimrc?

> You can add a hook to your preferred tree that is it's the only window remaining then execute a buffer delete on the tree window

I guess this would be the next best solution. Still suboptimal since I often don't want to close the tree when I delete a buffer. In that case I will than just use the keyboard to close buffers instead of the mouse. The mouse is still great if no tree is open.

Another solution would be if bufferline would allow the user to define which action should be performed when the right mouse-button is clicked. Then the user could define an action like `bn | bd#` to prevent the window from closing when deleting the buffer with the mouse.

**Comment by astier** [comment]
Another solution is just to focus another buffer before closing the old one.

**Comment by akinsho** [comment]
@astier there is a typo in the option in your config it should be `show_buffer_close_icons` you are missing an `s` on the end should be `icons` just tested it with that fixed and it works.

Regarding adding a custom function I'd rather not. At least not at the moment I haven't really got the time. I think this is more an issue with how `bd` works generally in vim and I could add something around that but tbh I think this is an issue that happens even without this plugin just by using the bd command.

**Comment by astier** [comment]
>there is a typo in the option in your config

Stupid mistake. Thank you for your help. Works now.

> Regarding adding a custom function I'd rather not. At least not at the moment I haven't really got the time.

No problem. Its not a dealbreaker.

> I think this is more an issue with how bd works generally in vim and I could add something around that but tbh I think this is an issue that happens even without this plugin just by using the bd command.

Yes it does happen by just using `bd`. I have the following mapping to prevent closing the window when deleting a buffer:

```vim
nnoremap <silent> <space>q :bn<bar>bd!#<cr>
```
