### ISSUE TITLE
Colors looks different after d6c226e8e05155101b202d7c94e1f9d1e4b2d145

### ISSUE THREAD

**Issue by Shatur95** [akinsho/nvim-bufferline.lua#107]
Before:
![изображение](https://user-images.githubusercontent.com/22453358/119557564-04a55980-bda9-11eb-863c-6add44eeab50.png)

After:
![изображение](https://user-images.githubusercontent.com/22453358/119557476-e7708b00-bda8-11eb-96be-19f6170d14a4.png)

After this change, it became more difficult to distinguish between open buffers because of vertical white line on each buffer. Also, this line after the current buffer is moved to the right after changing the current buffer.

Is this expected? Can I somehow get previous behavior?

**Comment by akinsho** [comment]
@Shatur95 no it wasn't intended I just refactored some very old functionality that hadn't changed since the plugin was created. I'll have a look in a bit at what I did differently/broke
