### ISSUE TITLE
Wrong devicon when .vimrc/.zshrc opened from startify screen

### ISSUE THREAD

**Issue by reportaman** [akinsho/nvim-bufferline.lua#110]
The result of ``:e .vimrc`` and ``:e ~/.vimrc`` is different. For the former, nvim-bufferline.lua does display file-specific devicon, for the latter it shows generic devicon. Please refer to the issue that I had originally filed on nvim-web-devicon repository below. It has the minimal .vimrc & a mp4 video that shows the problem. Thanks for this wonderful plugin!

https://github.com/kyazdani42/nvim-web-devicons/issues/58#issuecomment-844781143

**Comment by akinsho** [comment]
@reportaman this should be fixed now 👍🏾 , lemme know if not
