### ISSUE TITLE
Attempt to index 'bit' a nil value

### ISSUE THREAD

**Issue by aptigges21** [akinsho/nvim-bufferline.lua#111]

**Comment by aptigges21** [comment]
Thanks for the great work! Been using this plugin for a while now and really like it. However, I recently started receiving the following error: 
`E5108: Error executing lua ...lugged/nvim-bufferline.lua/lua/bufferline/colors.lua:72: attempt to index global 'bit' (a nil value)
`

My solution: per [https://bitop.luajit.org/api.html](url) I added `local bit = require("bit")` to the beginning of the colors.lua file and it worked. I would make a pull request but if no one else is having this problem I feel that is not necessary. I just thought if people do I'd made this issue so it's solved quickly. Feel free to close at any time or I will close on my own soon

**Comment by akinsho** [comment]
I'm going to close this out since this shouldn't really be an issue if using the correct version of lua/luajit 🤷🏾 will take a look if more people report this whilst on the on lua 5.1 with luajit

**Comment by dbarrosop** [comment]
I actually got the same issue. The funny bit is that I use nix and have exactly the same configuration/environment in two laptops and one of them works fine (older macbook pro with intel processor) and the other one gives the same exact issue (M1). In both cases I compiled nvim with nix:

```NVIM v0.5.0-dev
Build type: Release
Lua 5.1
Compilation:
Compiled by dbarroso

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/nix/store/98w4sbgfag4fjy7mp03ijj3n07y2qvdm-neovim-unwrapped-master/share/nvim"```

**Comment by akinsho** [comment]
I believe the issue here is that your nvim version doesn't seem to include `luajit`. When I run `version` on my machine, I get
```
LuaJIT 2.1.0-beta3
:version
NVIM v0.5.0-dev+1457-g2bcf18dea
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by dbarrosop** [comment]
Yeah, just realized the intel one has the same output as yours. Weird that the only issue is this one though, no other lua plugin seems to have problems with the difference (well, weird for me as I know very little about lua, I am sure it makes perfect sense). Anyway, will try to figure out why this is being compiled differently. Thanks for the quick response and the awesome plugin :)
