### ISSUE TITLE
Removing the empty bar

### ISSUE THREAD

**Issue by foodornt** [akinsho/nvim-bufferline.lua#112]
I'm trying to make the bar above transparent
![image](https://user-images.githubusercontent.com/40924367/120035993-1d5f7a80-c008-11eb-85b3-50f1816e9286.png)
Any idea what's wrong?

BTW When not using a colorscheme it just works, could it be because of the colorscheme? and if so, how can I solve it?

(The #FF0000 is just to show that the bar isn't getting affected)

**Comment by akinsho** [comment]
@foodornt the full list of highlight groups is in `:h bufferline-lua-styling` but the highlight group you're after should be fill. I just tried that locally and it worked. Can you check the output of `highlight BufferLineFill`. Also maybe make sure your colorscheme isn't messing with bufferline's highlights

**Comment by foodornt** [comment]
Could be the colorscheme. I'm using moonlight, if anybody happens to use the same colorscheme and have the same issue please let me know.

**Comment by akinsho** [comment]
@foodornt do you mean https://github.com/lewis6991/moonlight.vim colorscheme, in which case it doesn't look like it doesn't target bufferline. Tbh I really can't tell why it isn't working in your case. Can you try a completely minimal `init.lua` don't load anything else except this plugin and see if the color changes then try again with your colorscheme and see if it still works.

**Comment by akinsho** [comment]
@foodornt not sure what this ended up being due to but the bufferline fill highlight works on my various tests so going to close this out for now.

**Comment by lucasvianav** [comment]
Just to help anyone that may be wondering, [folke/tokyonight.nvim](https://github.com/folke/tokyonight.nvim) does [overwrite `BufferLineFill`](https://github.com/folke/tokyonight.nvim/blob/eede574f9ef57137e6d7e4bab37b09db636c5a56/lua/tokyonight/theme.lua#L372-L374).
