### ISSUE TITLE
Slant tab style doesn't work on terminals other than Kitty

### ISSUE THREAD

**Issue by siduck76** [akinsho/nvim-bufferline.lua#114]
Hi there! I have disabled the tab indicators and yet it shows 

![image](https://user-images.githubusercontent.com/59060246/120965188-2677e680-c782-11eb-842b-537f766e0dd2.png)

My config : 

![image](https://user-images.githubusercontent.com/59060246/120965100-00524680-c782-11eb-886b-420e22401d5a.png)

**Comment by siduck76** [comment]
the first tab doesnt even show any separators and for the rest of the tabs , it just shows only left separator 

![image](https://user-images.githubusercontent.com/59060246/120967239-e23a1580-c784-11eb-84b9-f8f5c24b3d5d.png)

separator config : 

![image](https://user-images.githubusercontent.com/59060246/120967334-f4b44f00-c784-11eb-8865-e6e98cb902ec.png)

**Comment by akinsho** [comment]
@siduck76 I think this is a misunderstanding, tab indicators are not the same as the buffer tabs, tab indicators are small indicators on the right hand side that show you if you have any tabs open.

![image](https://user-images.githubusercontent.com/22454918/120969095-a6418900-c761-11eb-807f-766dbeda1ff0.png)

I'm also not at all sure what the second set of screenshots is trying to do but to use the slanted indicators you can just set `separator_style = "slant"`

**Comment by siduck76** [comment]
@akinsho what is the difference between BufferLineBackground and BufferLineFill ( highlights )? Also how many highlights do you use for the separator?

**Comment by akinsho** [comment]
@siduck76 this isn't something that this plugin can fix, how these characters are rendered is determined by your terminal emulator 🤷🏾‍♂️ I use `kitty` which renders things correctly.

**Comment by siduck76** [comment]
oh :( , sadly all other terminals dont render it , even alacritty 

![image](https://user-images.githubusercontent.com/59060246/120971555-63e07200-c78a-11eb-9c93-472043820f17.png)

**Comment by siduck76** [comment]
Idk if this might work,  we can color the separators only and not their bgs 

![image](https://user-images.githubusercontent.com/59060246/120973159-34cb0000-c78c-11eb-814a-2e818b6d2b12.png)

**Comment by siduck76** [comment]
Also using these might work :

![image](https://user-images.githubusercontent.com/59060246/120973790-00a40f00-c78d-11eb-8600-0b47e17a4438.png)


instead of using these : 

![image](https://user-images.githubusercontent.com/59060246/120973811-0a2d7700-c78d-11eb-9d0d-7d943c220821.png)

**Comment by siduck76** [comment]
@akinsho terminal isnt the problem I think , its just that the left separator's slant glyph used needs to have a space after it :

before : 
![image](https://user-images.githubusercontent.com/59060246/120974987-604eea00-c78e-11eb-827c-d036157b9a9f.png)

output : 
![image](https://user-images.githubusercontent.com/59060246/120975025-6ba21580-c78e-11eb-97a9-eac8409b50ec.png)

after : 

![image](https://user-images.githubusercontent.com/59060246/120975148-896f7a80-c78e-11eb-8656-909288c1fdad.png)

output : 

![image](https://user-images.githubusercontent.com/59060246/120975190-93917900-c78e-11eb-90f7-c27253c75f99.png)

**Comment by akinsho** [comment]
@siduck76 does the other glyph have a space beside it already or does only one need it. It seems like a weird hack that only one to glyph needs a space. Does this break the appearance on other terminals?

**Comment by siduck76** [comment]
@akinsh Adding the space fixes this for all other terminals too , doesnt break any appearance too. 

I tested it on default alacritty , gnome-terminal ( didnt even set any nerdfonts in these) and it works :)

![image](https://user-images.githubusercontent.com/59060246/120978156-ce48e080-c791-11eb-861c-e055185d4121.png)

I suspected it cuz the left separator was hiding one " 

look close 
![image](https://user-images.githubusercontent.com/59060246/120978156-ce48e080-c791-11eb-861c-e055185d4121.png)

**Comment by siduck76** [comment]
oops , this fix works in all terminals but not kitty xD

![image](https://user-images.githubusercontent.com/59060246/120983726-9ba1e680-c797-11eb-8d3a-29fb847e6239.png)

**Comment by akinsho** [comment]
@siduck76 can you paste the separators with the whitespace you added here? I tried adding the spaces to the characters in my terminal and it looks fine, it makes the tabs thicker which I don't like but if it fixes things for more terminals 🤷🏾 I used `" ", " "` does that work for you?

**Comment by siduck76** [comment]
@akinsho here 

     " ", ""

**Comment by akinsho** [comment]
@siduck76 I think this plugin has *waaaay* too many options already I'd rather not add one for edge cases that a user shouldn't have to care about in the first place. Adding one whitespace char in a specific place seems kind of brittle/hacky I'm not sure why some terminals need that. It's worse still because if I do this I'll have to change the highlighting logic to handle this extra whitespace character which will be nasty. I'll have more of a think about doing this.

**Comment by siduck76** [comment]
@akinsho  adding one more option wouldnt be bad tho! Since this fixes a major issue regarding slant tab styling. It fixes all other terminals :D

**Comment by akinsho** [comment]
@siduck76 you misunderstand my issue. This problem doesn't need to be solved by adding an obscure option that people won't understand. Whatever the solution it should just work automatically without having to use an option. Probably if necessary I will check the terminal type and handle the whitespace automatically. Or I will just make the change for all terminals. I won't add this as an option.

The more tricky part is how to handle adding extra padding that doesnt make the highlighting for separators break or weird which is the bit that I'm saying will be a bit of a pain.

Since I'm the one probably doing the work myself I'll have a think about how to do it

**Comment by siduck76** [comment]
@akinsho the extra padding doesnt break the highlighting at all

**Comment by akinsho** [comment]
@siduck76 adding the extra padding *does* break the highlighting on kitty as you can see below. This needs to also be handled.

![image](https://user-images.githubusercontent.com/22454918/121001145-e2d1ac80-c782-11eb-9888-c4e5b27cef74.png)

**Comment by siduck76** [comment]
@akinsho yes as I said , this fix will break kitty but fix all other terminals! such a weird hack lol

**Comment by akinsho** [comment]
This should be fixed now I tested on gnome terminal and on alacritty and seemed fine, whilst also preventing breakage on kitty.

**Comment by siduck76** [comment]
Thanks works now :)
