### ISSUE TITLE
help with color customization

### ISSUE THREAD

**Issue by sbromberger** [akinsho/nvim-bufferline.lua#116]
I've read through `:h bufferline-styling` and the following sections, but I can't seem to get the colors the way I'd like.

Specifically, I'd like the separator to be invisible. I've tried setting `separator`, `separator_selected`, and various `indicator` settings, but none of these seem to work.

Could you please give me some advice on how to do this?

Thank you for a great plugin.

**Comment by akinsho** [comment]
@sbromberger can you share a screenshot of what specifically you are trying to hide? If it's the active indicator this has an `indicator_selected` group and you can set `guifg=NONE` you can also do a similar thing with the separators which should work. Alternatively you can set the `indicator_icon` to an empty string.

**Comment by sbromberger** [comment]
![9E8CABEA-BF69-4288-8FF5-48A930CFA54C](https://user-images.githubusercontent.com/941359/121098659-5811a180-c7c4-11eb-83c0-9f90036a7b14.jpeg)

The orange vertical bar is what I'm trying to eliminate. I tried `separator_style = {'', ''}` as well but it didn't do anything. Thank you!

**Comment by sbromberger** [comment]
I don't seem to have `indicator_selected`:

```
Failed setting BufferLineSeparator highlight, something isn't configured correctly
Vim(highlight):E411: highlight group not found: BufferLineSeparator
Failed setting BufferLineIndicatorSelected highlight, something isn't configured correctly
Vim(highlight):E411: highlight group not found: BufferLineIndicatorSelected
```

**Comment by sbromberger** [comment]
Ah, `indictor_icon = ''` worked. Thanks!
