### ISSUE TITLE
Hide close icon from visible buffers

### ISSUE THREAD

**Issue by siduck76** [akinsho/nvim-bufferline.lua#118]
Hi @akinsho , sorry to bother again! Is it possible to hide the close icon from all the buffers in bufferline? The selected buffer should only have the close icon.

By default every buffer has a close icon 

![image](https://user-images.githubusercontent.com/59060246/121281287-4d0a5e80-c8f5-11eb-9834-2cb8943c9e08.png)

Could look something like this : 
![image](https://user-images.githubusercontent.com/59060246/121281020-dd946f00-c8f4-11eb-8d92-54924f1ea361.png)

It'd be easy if the close icon's guifg takes colors from BufferlineBufferVisible's guibg color which will match the bg and hide it, hence making bufferline looking more clean and this would make the selected buffer look a bit different than the rest too :D

**Comment by akinsho** [comment]
@siduck76 I'm going to be spending less time adding new features or changes. This plugin takes too much of my time and for me has been in an acceptable state for months.

Regarding this specific feature a very important difference in the image you show is that in a GUI text editor you can hover over a tab and the `X` icon will appear so you don't lose the ability to close *any tabs* by pressing the close button.

I mentioned in a previous issue that nvim was looking at implementing hover functionality but that issue is years old so no real progress. The functionality you describe means that only the current tab will be closable by clicking which to me is *functionally* pointless since it's nvim and you can just press `ZZ` quicker than click the `X` button.

I think the only value to this feature without the hover functionality would be visual/aesthetic since it is functionally worse.

I won't personally implement this but will review a PR if one gets created. If nvim ever adds hover functionality then I would implement this with hover.

If you primary issue is with the close icons you can just hide them all if that is preferable.

**Comment by siduck76** [comment]
@akinsho close icons for inactive  / visible buffers is what I want to be hidden. I know there's no proper hover functionality in neovim. Is it possible to just add a highlight for close icon for BufferLineBufferVisible and BuffeLineBufferSelected , so it'll be easy to just make the inactive close icons to match their buffer bg colors which make them look hidden.

**Comment by akinsho** [comment]
@siduck76 a highlight group is an acceptable middle ground, but as I mentioned I won't be spending as much time on new features for this plugin. It's not a lot of work and you want this feature the most since I will not use it at all, so I think it would be worth you looking through the code base at how other highlights work an attempting a PR.

I maintain a few other plugins that also need my attention all of which distracts me from other things I do want to be working on in my free time that isn't just neovim plugins.

**Comment by akinsho** [comment]
@siduck76 I'd be happy to guide and help you with a PR, if you are configuring neovim in lua you'll probably have to learn some lua anyway and with what you learn you will be able to contribute some of the changes you want in the plugins you use, up to you 🤷🏾

**Comment by siduck76** [comment]
@akinsho I have moved my neovim [config](https://github.com/siduck76/NvChad) to full lua , I'd done the PR already if I was good at lua :p but Im still very new at it. Also making lua neovim plugins looks so hard :/ . My friend said we need to be good at vimscript , vim and know how the vim infrastructure works . My vim journey was too fast , I learned some vimtutor and directly jumped at neovim. I was using neovim only because I didnt like vscode and wanted to make an IDE like environment in cli itself , I didnt learn vimscript , it looks scary a few months later I directly jumped onto using lua plugins , they're so cool! And I configured neovim in lua now. Also idk where to start to learn making my own neovim plugins and idk their pre-requisites either :/

**Comment by akinsho** [comment]
@siduck76 I think that makes the bar way too high, you definitely don't need to know vimscript to get started with lua plugins. Almost all functionality ends up coming through the api which is all documented in `:help api`. But I think tbh the better way to approach contributing isn't to think about having to know everything first I think few plugin developers know everything.

It starts with just reading some code and adding a few lines or few conditional statements
In this case it would be

1. Add the new highlight group here defaulting to the same value as `background` e.g.
```lua
close_button_visible = {
  guifg = background_color,
  guibg = background_color
},
close_button_selected = {
  guifg = background_color,
  guibg = background_color
}
```
https://github.com/akinsho/nvim-bufferline.lua/blob/7b510d5241fb29f5a5e985e02c4cfa046ec4ee3e/lua/bufferline/config.lua#L153

2. Add the new highlight to the switch statement as `hl.close_button_selected`, `hl.close_button_visible` etc. for each branch
https://github.com/akinsho/nvim-bufferline.lua/blob/7b510d5241fb29f5a5e985e02c4cfa046ec4ee3e/lua/bufferline.lua#L126-L171

3. Use the highlight for the close button, change the function to pass in the full context and then get the new highlight value as `close_button.hl`
```lua
close_button.hl .. icon
```
https://github.com/akinsho/nvim-bufferline.lua/blob/7b510d5241fb29f5a5e985e02c4cfa046ec4ee3e/lua/bufferline.lua#L275

**Comment by siduck76** [comment]
@akinsho I'll test this locally first and then try! thx for the help

**Comment by siduck76** [comment]
> @siduck76 I think that makes the bar way too high, you definitely don't need to know vimscript to get started with lua plugins. Almost all functionality ends up coming through the api which is all documented in `:help api`. But I think tbh the better way to approach contributing isn't to think about having to know everything first I think few plugin developers know everything.
> 
> It starts with just reading some code and adding a few lines or few conditional statements
> In this case it would be
> 
> 1. Add the new highlight group here defaulting to the same value as `background` e.g.
> 
> ```lua
> close_button_visible = {
>   guifg = background_color,
>   guibg = background_color
> },
> close_button_selected = {
>   guifg = background_color,
>   guibg = background_color
> }
> ```
> 
> https://github.com/akinsho/nvim-bufferline.lua/blob/7b510d5241fb29f5a5e985e02c4cfa046ec4ee3e/lua/bufferline/config.lua#L153
> 
> 1. Add the new highlight to the switch statement as `hl.close_button_selected`, `hl.close_button_visible` etc. for each branch
>    https://github.com/akinsho/nvim-bufferline.lua/blob/7b510d5241fb29f5a5e985e02c4cfa046ec4ee3e/lua/bufferline.lua#L126-L171
> 2. Use the highlight for the close button, change the function to pass in the full context and then get the new highlight value as `close_button.hl`
> 
> ```lua
> close_button.hl .. icon
> ```
> 
> https://github.com/akinsho/nvim-bufferline.lua/blob/7b510d5241fb29f5a5e985e02c4cfa046ec4ee3e/lua/bufferline.lua#L275

I dont understand the third step :(

**Comment by siduck76** [comment]
@akinsho I'll test this locally first! thx for the help. I dont get the 3rd step

**Comment by akinsho** [comment]
@siduck76 nah sorry wasn't super clear you need to change it where the `symbol` variable is being used
like
```lua
return "%" .. buf_id .. "<long-stuff-here>".. close_button.hl .. symbol, size
```
Also note that this function `close_icon` takes only the `options` not the `highlights` because where it is being called it is probably only being called with `ctx.options` but should be called with `close_icon(buf_id, ctx)`

so inside the function you can do
```lua
local buffer_close_icon = ctx.options.buffer_close_icon
local close_button_hl = ctx.current_highlight.close_button.hl -- this will depend on what you name it in step 2
```

**Comment by siduck76** [comment]
@akinsho I defined close_button_visible.hl and close_button_selected.hl , where do I define close_button.hl? in the else section?
 
![image](https://user-images.githubusercontent.com/59060246/121381606-7c57b480-c963-11eb-907c-484a5e028ecb.png)

**Comment by akinsho** [comment]
@siduck76 that's in step `1.` you need to add `close_button = {guifg = <blah>, guibg = <blah>}` etc. for the other types inside `config.lua` they should get passed through to here (unless I'm forgetting something, that's all already been hooked up)

**Comment by siduck76** [comment]
@akinsho so the step 1 has these three in config.lua right? 
![image](https://user-images.githubusercontent.com/59060246/121394920-78ca2a80-c96f-11eb-8ed5-24bb6ba2843f.png)

**Comment by akinsho** [comment]
@siduck76 in the line at the bottom at the return you are re-using the variable you created on line 276 so you should use `close_button_hl`.

**Comment by akinsho** [comment]
From the screenshot above you are also not passing in `ctx` just `options` you need to change the place where `close_icon` is called to pass in `ctx` and change the variable name in the definition of `close_icon` to `ctx`

**Comment by siduck76** [comment]
> From the screenshot above you are also not passing in `ctx` just `options` you need to change the place where `close_icon` is called to pass in `ctx` and change the variable name in the definition of `close_icon` to `ctx`

ctx doesnt seem to be a function , how do I pass close_icon in it? I didnt find any close_icon related code in this function too

![image](https://user-images.githubusercontent.com/59060246/121397471-f8f18f80-c971-11eb-841b-f5845e3414c9.png)

**Comment by akinsho** [comment]
@siduck76 ctx is not a function it is a `table` what I'm saying is that at some point `close_icon` is being called with 2 arguments you need to find where it is being called and change the second argument to pass in this object which will already be available where it is being called. Have a look around just grep the code base for the name `close_icon`

**Comment by siduck76** [comment]
@akinsho This is getting confusing! I have to change the second argument and add it as a variable in ctx table?

![image](https://user-images.githubusercontent.com/59060246/121400176-e62c8a00-c974-11eb-8994-6dcdef060ca8.png)

**Comment by akinsho** [comment]
@siduck76 The line below is where `context` is passed in. This is the table we have been discussing and that you showed in your screenshot.

https://github.com/akinsho/nvim-bufferline.lua/blob/7b510d5241fb29f5a5e985e02c4cfa046ec4ee3e/lua/bufferline.lua#L333

On the line below you need to change `something` to pass in `context` instead
https://github.com/akinsho/nvim-bufferline.lua/blob/7b510d5241fb29f5a5e985e02c4cfa046ec4ee3e/lua/bufferline.lua#L342

**Comment by siduck76** [comment]
@akinsho is this right? 

![image](https://user-images.githubusercontent.com/59060246/121454425-63312100-c9c0-11eb-8f67-e1bc2ef94998.png)

**Comment by akinsho** [comment]
@siduck76 did you change the place where close icon is being called to correctly pass on the context table?

**Comment by siduck76** [comment]
@akinsho Im confused again , I changed the second argument in context table's , close_icon function 
 
 
![image](https://user-images.githubusercontent.com/59060246/121528348-001fa880-ca19-11eb-9925-bd0135ab0e10.png)

**Comment by akinsho** [comment]
@siduck76 this might be easier if you make a *Draft PR* then I can just make comments on github rather than doing it with screenshots

In this case what I'm saying is that
```lua
local close, size = close_icon(buffer.id, context) --< after buffer id should be context
```
