### ISSUE TITLE
Pick buffer by number

### ISSUE THREAD

**Issue by wirtsi** [akinsho/nvim-bufferline.lua#120]
Hello

might be that I am blatantly missing this from the docs .... but how can I jump to a buffer by ordinal number? So something like <leader>1 opens the first buffer

Thnx :-)

**Comment by akinsho** [comment]
@wirtsi a user can set the mappings key to `true` and this plugin will create `<leader>1-9` mappings to open a buffer by oridinal number. NOTE: the key isn't `mappings` it should be in the README I don't recall what it's called atm

**Comment by wirtsi** [comment]
Hey @akinsho 

Thanks ... I tried the mappings key in the config, there seems to be a bug in the way nvim-bufferline sets the keys though

![image](https://user-images.githubusercontent.com/276751/121660379-7ff25500-caa3-11eb-8fe5-91f4fdc10792.png)

So it somehow seems to prefix the number with a backslash, that's probably not intended ...

**Comment by akinsho** [comment]
@wirtsi that's not a bug I don't think. The default `<leader>` key for neovim is `\` if you have not changed your `<leader` then this is the expected behaviour. You shouldn't/ I won't add number mappings like `1-9` directly because this will break all other behaviour in neovim that expects a count like `2dw` etc.

**Comment by wirtsi** [comment]
I have configured the <leader> the be the space key (backslash is not so nice to reach on my keyboard layout) ... I checked the code and found out what the issue was:

I was setting the leader key below the plugged config (where I am loading nvim-bufferline) ... moving the definition above it fixed the problem for me

Thanks for your help
