### ISSUE TITLE
Feature request: allow buffer switching by ordinal number

### ISSUE THREAD

**Issue by krims0n32** [akinsho/nvim-bufferline.lua#121]
Thank you for this awesome plugin. I have one feature request, I would like to be able to switch buffers using the ordinal buffer numbers displayed.

This way I can map <leader>1 to switch to buffer with ordinal number 1, 2 for 2, etc.

**Comment by akinsho** [comment]
@krims0n32 please see #120

**Comment by krims0n32** [comment]
Thank you sir!
