### ISSUE TITLE
Each tab has an extra bar at the back

### ISSUE THREAD

**Issue by Racle** [akinsho/nvim-bufferline.lua#125]
Some (recent) update broke bufferline.

![image](https://user-images.githubusercontent.com/759091/121856744-854adc00-ccfd-11eb-85c2-cfde362f9529.png)

My bufferline config:

```lua
require "bufferline".setup {
  highlights = {
    fill = {
      guibg = "#282828"
    },
    separator_selected = {
      guifg = "#282828"
    },
    separator_visible = {
      guifg = "#282828"
    },
    separator = {
      guifg = "#282828"
    }
  },
  options = {
    modified_icon = "●",
    left_trunc_marker = "",
    right_trunc_marker = "",
    max_name_length = 25,
    max_prefix_length = 25,
    enforce_regular_tabs = false,
    view = "multiwindow",
    show_buffer_close_icons = false,
    show_close_icon = false,
    separator_style = "slant",
    offsets = {
      {
        filetype = "coc-explorer",
        text = "File Explorer",
        highlight = "Directory",
        text_align = "center"
      }
    }
  }
}
```

**Comment by akinsho** [comment]
Hi @Racle,

what terminal are you using? did you just switch to `slant` for the first time? or were you using `slant` before. Just as a note it won't work on every terminal but if you are on one of the supported terminals I'll try and see what's going on

**Comment by Racle** [comment]
@akinsho I'm using Tilix.

I've been using this terminal for years. And I switched to bufferline and to this config earlier without problems.

Some update in last 2 weeks broke my config/bufferline.

**Comment by akinsho** [comment]
😓 this relates to #114, the TLDR is that different terminal handle rendering the slant characters differently, some terminal need an extra space some don't 😭 , it's a bit of a nightmare. Do you know how I can detect if a terminal is tilix or not?

**Comment by Racle** [comment]
@akinsho got zero idea about that.
`ps -p$PPID -o cmd=` seems to find tilix that BUT it doesn't work inside tmux which I also use (it displays that I'm using tmux, not tilix).

Maybe add an option to disable this fix https://github.com/akinsho/nvim-bufferline.lua/commit/54576f262e4ef5ea7a31d88b2d1399f637e338d2 ?

Usually people don't use multiple terminal emulators so that might be enough (at least until better method is found).

**Comment by akinsho** [comment]
@Racle I really don't want to have this be an option since it is an obscure bug and an option will be hard to explain. Also I think this plugins complexity and the number of options has gotten too wild.

I think what I will do is see if there are any ways to detect `tilix`, if not I might just add it to the list of terminals that are *not* supported. Either that or I think the `slant` option has ended up being a lot of trouble, I might consider deprecating it since it's causing me a lot of headaches.

**Comment by Racle** [comment]
Quick workaround for this if someone else finds this, I added this before `require "bufferline".setup` and it seems to be working just fine
```lua
vim.api.nvim_exec([[let $KITTY_WINDOW_ID=0]], true)
``` 

<sub>I was sure I made this comment few hours ago (probably forgot to press comment :man_shrugging:)</sub>

**Comment by Joakker** [comment]
> Quick workaround for this if someone else finds this, I added this before `require "bufferline".setup` and it seems to be working just fine
> 
> ```lua
> vim.api.nvim_exec([[let $KITTY_WINDOW_ID=0]], true)
> ```
> 
> I was sure I made this comment few hours ago (probably forgot to press comment man_shrugging)

Works like a charm in Konsole. You also apparently don't need to define it before loading the plugin. It works just as well if you do it afterwards
