### ISSUE TITLE
Integration akinsho / nvim-bufferline.lua with Lualine

### ISSUE THREAD

**Issue by Trid-collab** [akinsho/nvim-bufferline.lua#126]
Is it possible to integrate the Lualine features with those of 'bufferline' . Basically I was wanting color highlighting I am getting in statusline in the tabline along with the benefits of the "akinsho / nvim-bufferline.lua" plugin.

I like how earlier airline enabled the highlighting of bufferline

**Comment by akinsho** [comment]
@Trid-collab I'm not sure I fully understand this request, but tbh I won't be doing any integrating in this plugin with other ones. I think these things should be decoupled and where/if necessary an api or functionality provided for a user to do this themselves. A user can tweak most of bufferline's highlights so you can find what colours you like and add those to your config.

**Comment by akinsho** [comment]
Going to close this since I think I've answered the question.
