### ISSUE TITLE
Suggestion: Custom Area example improvements

### ISSUE THREAD

**Issue by spiderpug** [akinsho/nvim-bufferline.lua#128]
The given custom area example is working in general, but only if all 4 lsp diagnostics are greater than zero. It does not show the right area when only informations are present -- at least I could not make it work.

Note the replacement of `result[0] = ` with `table.insert`. This configuration fixed it for me:

```lua
        custom_areas = {
            right = function()
                local result = {}
                local error = vim.lsp.diagnostic.get_count(0, [[Error]])
                local warning = vim.lsp.diagnostic.get_count(0, [[Warning]])
                local info = vim.lsp.diagnostic.get_count(0, [[Information]])
                local hint = vim.lsp.diagnostic.get_count(0, [[Hint]])

                if error ~= 0 then
                    table.insert(result,
                                 {text = "  " .. error, guifg = "#EC5241"})
                end

                if warning ~= 0 then
                    table.insert(result,
                                 {text = "  " .. warning, guifg = "#EFB839"})
                end

                if hint ~= 0 then
                    table.insert(result,
                                 {text = "  " .. hint, guifg = "#A3BA5E"})
                end

                if info ~= 0 then
                    table.insert(result,
                                 {text = "  " .. info, guifg = "#7EA9A7"})
                end
                return result
            end,
        },

```

**Comment by akinsho** [comment]
Hi @spiderpug, tbh all the examples in the README are just to trigger some inspiration for users. They are definitely not intended to cover all edge cases etc. They are definitely *best effort-ish*, that particular example is from another user. If you managed to make an improvement though I'd appreciate it if you can raise a PR to update the README.

**Comment by spiderpug** [comment]
> Hi @spiderpug, tbh all the examples in the README are just to trigger some inspiration for users. They are definitely not intended to cover all edge cases etc. They are definitely _best effort-ish_, that particular example is from another user. If you managed to make an improvement though I'd appreciate it if you can raise a PR to update the README.

Hi @akinsho , appreciate your input. I understand that the examples are not covering all use cases, and they never could. If you think this is a worthy addition, I'm happy to PR something. If you think the current example is clear enough, I'm also fine with leaving it as-is. Could also be me lacking Lua skills, to anticipate that this behaviour was intended.

WDYT?

**Comment by akinsho** [comment]
@spiderpug I think an example that always shows all values sounds like a good default since it's probably what other people expect, so a PR would be great. Tbh the original example was an excerpt from another user's dotfiles and I think they probably intended for it to only show if there were multiple values 🤷🏾

**Comment by akinsho** [comment]
@spiderpug are you still up for creating the example update PR? Otherwise, I might close this issue and people can find it later still.

**Comment by spiderpug** [comment]
Fixed in https://github.com/akinsho/nvim-bufferline.lua/pull/132 ❕
