### ISSUE TITLE
[Feature request] custom names

### ISSUE THREAD

**Issue by pwntester** [akinsho/nvim-bufferline.lua#130]
Hi!

I was wondering if it could be possible to allow changing the name appearing in the tabline items. My use case is that if the buffer name starts with `octo:/` I would like to show a text with a truncated version of the github issue that the buffer represents.

Thanks
A

**Comment by akinsho** [comment]
Hi @pwntester,

This isn't too complicated a feature to add, and It could have some cool use cases. What concerns me is that people are almost certainly going to abuse this to change things other than the sort of use case you describe, which will very probably break the plugin and result in issues like "why can't I make x name work" etc. I guess this could be solved by stern documentation, I'm just wary of opening the floodgates to a range of issues regarding buffer names.

**Comment by akinsho** [comment]
Closed by #131

**Comment by pwntester** [comment]
Thanks!
