### ISSUE TITLE
Icon bg color linked to selected buffer color

### ISSUE THREAD

**Issue by litearc** [akinsho/nvim-bufferline.lua#137]
Hi, thanks for the awesome plugin!

I'm trying to change the bufferline colors, and ran into two (unrelated?) issues:
- the bg color of the (nvim-web-devicons) icons is mapped to the fg color of the buffer text, as seen below: 
<img width="147" alt="text-white" src="https://user-images.githubusercontent.com/1840363/124402248-05f96880-dcfd-11eb-8d8b-0aea8965c98d.png">
<img width="147" alt="text-blue" src="https://user-images.githubusercontent.com/1840363/124402249-07c32c00-dcfd-11eb-9d10-5228d8e4e55b.png">
- for some reason, to set the buffer text color (white in the first pic above, blue in the second), I had to set 'guibg', not 'guifg' like I would expect, e.g. to set the text color to blue, I had to do:

```
require('bufferline').setup{
  highlights = {
    buffer_selected = {guifg = colors.black, guibg = colors.blue},
  }
}
```
This is also the case with the 'duplicate*' highlights and possibly others. Am I doing something wrong, or is this a bug? Thanks!

Edit: it seems the issue is related to tmux, which I usually run neovim inside of. Both the above problems don't occur outside tmux. If you know of a solution, that would be great, but since it seems tmux-related, maybe it's ok to close this.

**Comment by akinsho** [comment]
@litearc I'm really not sure I follow what is happening tbh. I know tmux can cause strange highlighting issues, but haven't encountered any for quite a while on my setup. Can you confirm that the `reverse` option isn't maybe being set by something in your colorscheme or in some part of your config affected by tmux? you can check if your highlight groups are picking up `reverse` somehow by running `:highlight <name-of-group>` and seeing if something has set reverse

Really not sure about how to help re. the tmux part of things, that's beyond the scope of this plugin tbh.

**Comment by litearc** [comment]
I'm not sure what you mean by `reverse`, but I tried setting `gui = 'none'`, and that seemed to do the trick. It may be how tmux handles bold text. Either way, I agree this is beyond the scope of the plugin, so I'm closing the issue. Thanks!
