### ISSUE TITLE
Closing behaviour with Nvim Filetree

### ISSUE THREAD

**Issue by Davincible** [akinsho/nvim-bufferline.lua#140]
Normally, when you close one of multiple buffers, it detects that there are still other buffers open, and opens a window with one of the other buffers. However, when I have the file tree open, and I close one of the multiple buffers, by clicking on the close button, it detects the file tree buffer as a 'regular' buffer like any other file, and just shows it full screen. 

This is bit cumbersome, as then I have to manually click on another buffer, which causes the filetree buffer to be shown to the right, instead of the default left, and close and reopen the file tree to get the normal layout back. It would be much nicer if the plugin detected that the only buffer still visible is the file tree buffer, and then just like normally, show a window with one of the other open file buffers.

This also influences the autoclose behavior of file tree, which closes nvim entirely if filetree is the only visible buffer left. But when the current visible buffer gets closed, even though there are still other hidden buffers, nvim closes entirely. 

Thus by opening a new window with one of the other file buffers, both of these issues could be solved.

**Comment by akinsho** [comment]
@Davincible so this issue you're describing is a more general nvim/vim issue in that the drawer windows *are regular buffers* vim doesn't distinguish between them and other buffers, so they behave just like any other buffer would. There are actually [articles](http://vimcasts.org/blog/2013/01/oil-and-vinegar-split-windows-and-project-drawer/) and posts that touch on this

Tbh I think it's out of scope for this plugin, to be clear the plugin isn't actually really handling closing buffers it just call the native nvim `bufdelete` functionality which is what actually handles what happens next. I don't think it's this plugin's responsibility to handle a user's window layout or anything like that. This should be done by users or other plugins. In this case, you can override the behaviour of the click command and try to make it behave differently based on what conditions you'd like.

I think it might be worth raising this with nvim tree (I think there are already a few issues on this subject) but don't think this is something to be dealt with here.

**Comment by librowski** [comment]
For anyone encountering this issue - the function below handles closing tabs pretty well. I just bound it to `<Leader>q`:
```lua
local function closeBuffer()
  local treeView = require('nvim-tree.view')
  local bufferline = require('bufferline')

  -- check if NvimTree window was open
  local explorerWindow = treeView.get_winnr()
  local wasExplorerOpen = vim.api.nvim_win_is_valid(explorerWindow)

  local bufferToDelete = vim.api.nvim_get_current_buf()

  -- TODO: handle modified buffers
  -- local isModified = vim.api.nvim_eval('getbufvar(' .. bufferToDelete .. ', "&mod")')

  if (wasExplorerOpen) then
    -- switch to previous buffer (tracked by bufferline)
    bufferline.cycle(-1)
  end

  -- delete initially open buffer
  vim.cmd('bdelete! ' .. bufferToDelete)
end

```

**Comment by feluxe** [comment]
This is a solution which wraps the `BufferLineCycleNext` and `BufferLineCyclePrev` functions, rather than acting on quit/delete:

When you get stuck in a buffer like `nvim-tree` with no other active tab showing, you can use your `tab-next` / `tab-prev` shortcuts to get back to the first tab and continue using BufferLine.

```lua
local function bufferline_get_current_index(current_state)
  for index, component in ipairs(current_state.components) do
    if component:current() then
      return index
    end
  end
end

local function tab_cycle(direction)
    local bufferline = require('bufferline')
    local state = require("bufferline.state")

    local index = bufferline_get_current_index(state)

    if index == nil then
      -- If no tab is currently active, we switch to the first tab.
      bufferline.go_to_buffer(1)
    else
      -- Cycle next tab
      bufferline.cycle(direction)
    end
end

function TabCycleNext()
  tab_cycle(1)
end

function TabCyclePrev()
  tab_cycle(-1)
end

vim.cmd([[command! TabCycleNext lua TabCycleNext()]])
vim.cmd([[command! TabCyclePrev lua TabCyclePrev()]])

```

Just map the `TabCycleNext` and the `TabCyclePrev` to your preferred keys.

**Comment by akinsho** [comment]
I highly advise against using internal bufferline state e.g. require('bufferline.state') this is definitely a private module and wouldn't even be visible if there was a way to hide modules in lua easily, it's likely to change at any given moment since I very much depend on being able to change it without worrying about breakages

**Comment by DG9Jww** [comment]
> 

hi，@librowski
Thanks for your great solution.
However,an error occured when I closed buffer without nvim-tree.
The reason is:
```lua
local wasExplorerOpen = vim.api.nvim_win_is_valid(explorerWindow)
``` 
This function return nil when I was not using nvim-tree.So I add some other code to prevent this error.
```lua
...
  local explorerWindow = treeView.get_winnr()
  if explorerWindow == nil then 
    vim.cmd('bdelete! ')
    return
  end
  local wasExplorerOpen = vim.api.nvim_win_is_valid(explorerWindow)
...
```
Now,it's good.
