### ISSUE TITLE
Integrate with `buf-num-nav.nvim`

### ISSUE THREAD

**Issue by winston0410** [akinsho/nvim-bufferline.lua#143]
I came across https://github.com/akinsho/nvim-bufferline.lua/blob/0e1fa3ddc350f8943317015ce0c3b96c30e84444/lua/bufferline.lua#L900 when I read the source of bufferline, do you think it is a good idea to integrate what I have in there instead?

**Comment by akinsho** [comment]
Hi @winston0410,

I don't think I understand what this is issue is about really, but judging from the name about integrating another plugin, I've been asked this before, and generally I don't want anyone using this plugin to have any dependencies (other than icons).

This is also a very small bit of logic, so I don't think an external plugin is necessary for it at all. Lastly, I eventually plan to refactor the mappings, so they work with a user's visible buffers not just absolute numbers, which will require the mappings working with internal state, so a plugin wouldn't work with that.
