### ISSUE TITLE
diagnostics_indicator only gives out "error" for `level`

### ISSUE THREAD

**Issue by winston0410** [akinsho/nvim-bufferline.lua#144]
Right now `diagnostics_indicator` only gives out `"error"` for `level`, mixing up `"warning"` and `"error"`

**Comment by winston0410** [comment]
I am not sure if it is really a bug in implmentation or it is intended (which then I guess need clarification in doc). Is the first parameter intended to be total count instead of the count for messages in specific levels, and is the second parameter intended to be the highest level of error instead of the level of the error being emitted?

https://github.com/akinsho/nvim-bufferline.lua/blob/344564ab6a5e5417e899f15818f53c812dfea287/lua/bufferline/diagnostics.lua#L84

Anyway, I am able to conditionally apply icons with the third parameter.

**Comment by akinsho** [comment]
@winston0410 the count is the absolute number of issues of any kind warning, error, or info. The diagnostics level is the highest level of issue, e.g. if there are 10 warnings and 1 error, it will be an error. I would remove the first two parameters if I could and a user would just use the 3,4 (or event combine them) but I don't know who uses this and how, and it will break their configs.

If it's not clear I'd definitely welcome a PR to update the docs, keeping up with all the documentation in markdown and vim docs is time-consuming and error-prone and there's definitely missing bits.

**Comment by akinsho** [comment]
Actually it is in the documentation under `:help bufferline-lua-diagnostics` although that hasn't been updated to include the third and fourth arguments.

**Comment by winston0410** [comment]
I see. I will then close it. Thanks.
