### ISSUE TITLE
Bufferline disappears when opening the first file

### ISSUE THREAD

**Issue by ouuan** [akinsho/nvim-bufferline.lua#145]
After #141, the bufferline disappears when:

1.  Open an empty NeoVim session.
2.  Open a file (via either `:e` or fzf).
3.  The bufferline disappears.
4.  Open another file.
5.  The bufferline appears.

**Comment by akinsho** [comment]
@ouuan sorry about that, should be fixed now. I reproduced it on a minimal config and retried after the fix and that seems to have resolved the issue. Thanks for reporting it
