### ISSUE TITLE
Custom Area Async datetime

### ISSUE THREAD

**Issue by sphynx79** [akinsho/nvim-bufferline.lua#148]
Hello please can you help me to insert async datetime in custom area.

Now i use this code to insert datetime in custom area:

```
        custom_areas = {
          right = function()
            local result = {}
            table.insert(result, {text = ' ' .. '  ' .. os.date('%H:%M') .. ' ' , guifg = "#EC5241"})
            return result
          end,
        },

```

But i want refresh datetime every minute in async mode.

**Comment by akinsho** [comment]
@sphynx79 this is quite a bit out of the scope of this plugin, i.e. how to implement a clock in lua doesn't really specifically relate to this plugin. I haven't done this before myself, so I don't actually know off the top of my head, but guess you would need to use a timer using `vim.loop.timer_start` and then redraw the section every minute. I guess the best way to do this would be to literally call `redrawtabline` inside your timer. Keep in mind that doing this will mean having to redraw your tabline every minute, but that's not a huge deal, maybe.

Good luck, feel free to post your solution here if you figure it out so maybe anyone else with a similar request in the future if it comes up will know how to do it.

**Comment by aemonge** [comment]
Found out a solution for this?   I know it's outside the scope, but just wondering if you, @sphynx79 , did it
