### ISSUE TITLE
Can I ues BufferLinePick to close a buffer?

### ISSUE THREAD

**Issue by KeqiZeng** [akinsho/nvim-bufferline.lua#150]
Hello bro, I don't use mouse in neovim, so I want to know can I use the function `BufferLinePick` to close a buffer just like pick it. If yes, can you tell me how to get it?
Thank you so much!!

**Comment by akinsho** [comment]
@KeqiZeng that isn't possible currently, it's an interesting idea though. I'm probably not going to look into it myself anytime soon, but would appreciate/review a PR for it though

**Comment by ramezgerges** [comment]
@akinsho I gave it a try (#153).

**Comment by akinsho** [comment]
This is fixed by #153 which added the `BufferLinePickClose` command

**Comment by KeqiZeng** [comment]
OK, I'll try it. Thank you bro!
