### ISSUE TITLE
[Bug report] tab close button not working

### ISSUE THREAD

**Issue by moshiur-raj** [akinsho/nvim-bufferline.lua#155]
Clicking the close icon does nothing when multiple tabs are open. And I could not find any separate mappings for that close icon. There seems to be one available for the close icon displayed after the buffer name.

**Comment by akinsho** [comment]
Hi @moshiur-raj,

Hmm that icon is very old, I wouldn't be surprised if it broke at some point in the past and you're the first person to report the issue. Tbh I don't use any of the clicking functionality personally so hadn't noticed.

**Comment by moshiur-raj** [comment]
Thank you.

**Comment by ljmf00** [comment]
@akinsho Apparently, this doesn't work again.
