### ISSUE TITLE
[Bug] Clicking the bufferline fill region closes tabs and buffers

### ISSUE THREAD

**Issue by mintelm** [akinsho/nvim-bufferline.lua#157]
Hi,

when I disable the option `show_close_icon` I can still click the icon even though it is not rendered and the buffer will be closed.
I know there is the option `close_command` but this changes the behavior of all close buttons. I simply want to hide and deactivate the one on the far right of the bufferline, not the ones inside of the buffer "tab".

What I expected:
Disabling the option should also disable the functionality. Or add a new option to disable it beeing clickable.

Greetings,
Mario

**Comment by akinsho** [comment]
@mintelm I just had a try and I'm not sure I understand what you mean. On my end if I set the `show_close_icon = false` the right most cross icon disappears, the logic it uses is also not in the bufferline *at all* there is nothing to click, so I'm not sure how it's possible that it's triggering anything? Are you mixing the tab close button with the buffer close buttons?

**Comment by akinsho** [comment]
I also just tried disableing the buffer close icons using `show_buffer_close_icon` and that also hides the icons *per buffer tab* and clicking on it doesn't close the buffer either. Can you share some screenshots or a GIF of what you mean?

**Comment by mintelm** [comment]
![Peek 2021-07-21 14-33](https://user-images.githubusercontent.com/46969863/126489037-a8a86184-72fb-45e6-af54-5f77243e9fa8.gif)

**Comment by mintelm** [comment]
You see how I click the hidden close button and it closes my tabs?

**Comment by akinsho** [comment]
@mintelm thanks for the GIF, was able to reproduce it. Somehow the click component is "leaking" into the empty section. Anyway I'll look into it when I get a chance got quite a backlog of issues across multiple plugins so probably won't be soon. I always welcome a PR if you are willing to dig in yourself otherwise it's a waiting game.

**Comment by akinsho** [comment]
This should now be fixed by 47fc74b 🤞🏿
