### ISSUE TITLE
VimEnter error

### ISSUE THREAD

**Issue by Shatur** [akinsho/nvim-bufferline.lua#159]
After e211a5495d5f90209382ebd242b086f729ad2e74 I have the following errors that happen on VimEnter:

```
Failed setting BufferLineDuplicate highlight, something isn't configured correctly: Vim(highlight):E418: Invalid value: guifg=#5d646d
Failed setting BufferLineDuplicateSelected highlight, something isn't configured correctly: Vim(highlight):E418: Invalid value: guifg=#5d646d
Failed setting BufferLineDuplicateVisible highlight, something isn't configured correctly: Vim(highlight):E418: Invalid value: guifg=#5d646d

**Comment by akinsho** [comment]
@Shatur can you paste what you set as the value for those highlights in your config, maybe I missed a field

**Comment by Shatur** [comment]
> @Shatur can you paste what you set as the value for those highlights in your config, maybe I missed a field thinking.

I have the same behavior even without a colorscheme. I have the same error every startup.
The plugin is loaded via native package manager using `:packadd! nvim-bufferline.lua`

**Comment by Shatur** [comment]
Here is what I have after loading:
![изображение](https://user-images.githubusercontent.com/22453358/126702029-bfc89b3c-f294-406a-9492-15739b5199c6.png)
![изображение](https://user-images.githubusercontent.com/22453358/126702059-b0d587a2-08bb-4990-8226-c92c4914e533.png)
![изображение](https://user-images.githubusercontent.com/22453358/126702085-f256fb48-f18e-4edb-b80f-141939f38f60.png)

**Comment by akinsho** [comment]
@Shatur can you try with a minimal `init.lua` I just tried with `nvim -u <minimal.lua> --noplugin`
with just
```lua
-- minimal.lua
vim.cmd([[packadd! nvim-bufferline.lua]])

vim.opt.termguicolors = true
require("bufferline").setup({})
```
And I don't see this error. Are you doing anything in your config to change these colors or in the setup of this plugin

**Comment by akinsho** [comment]
Actually, you must be changing these colours somewhere because the default styles are different from what your highlight command shows.

**Comment by Shatur** [comment]
Right, sorry, I should have started with this, I found the reason:

```lua
require('bufferline').setup({
  highlights = {
    buffer_selected = {
      gui = 'bold',
    },
    warning_selected = {
      gui = 'bold,underline',
    },
    error_selected = {
      gui = 'bold,underline',
    },
    duplicate_selected = {
      gui = '',
    },
    duplicate_visible = {
      gui = '',
    },
    duplicate = {
      gui = '',
    },
    pick_selected = {
      gui = 'bold',
    },
    pick_visible = {
      gui = 'bold',
    },
    pick = {
      gui = 'bold',
    },
  },
})

I simply disabling italic. Is there anything I should do with my configuration?

**Comment by akinsho** [comment]
Ah I see the issue. The gui field is passed right to the highlight command which is why it is erroring since it will be creating `highlight Thing gui= guifg=value` it's best to put `NONE` there really, but I'll also add a change to check for invalid values and use non if it finds any, still that shouldn't be something to rely on specifically since I won't be checking stuff like if a user puts 'hello' or whatever that will still error.

**Comment by Shatur** [comment]
>  The gui field is passed right to the highlight command which is why it is erroring since it will be creating highlight Thing gui= guifg=value it's best to put NONE there really

Thanks, this solves the issue for me.

> but I'll also add a change to check for invalid values and use non if it finds any

I would ok with the error. An string just worked before, so I was surprised :)
