### ISSUE TITLE
separator not changing

### ISSUE THREAD

**Issue by ChrisTsou** [akinsho/nvim-bufferline.lua#161]
![Screenshot 2021-07-23 190939](https://user-images.githubusercontent.com/25465975/126810772-9259d49b-e0e8-4fb1-9025-9bb42ae10e75.png)

tried all available values its the same. i have nerd font.

**Comment by akinsho** [comment]
@ChrisTsou can you paste your config and show what values you tried changing and what to?

**Comment by akinsho** [comment]
From the README
> separator_style = "slant" | "thick" | "thin" | { 'any', 'any' },
this is how to change the separators,
to change the indicator use the `indicator_icon` options.

**Comment by ChrisTsou** [comment]
I've tried all 'slant', 'thick', 'thin' , {'/', '\'}. It looks exactly the same on all cases

**Comment by ChrisTsou** [comment]
im stupid, forgot the "options" field. my bad.
