### ISSUE TITLE
Highlight

### ISSUE THREAD

**Issue by ChrisTsou** [akinsho/nvim-bufferline.lua#162]
![Screenshot 2021-07-24 001653](https://user-images.githubusercontent.com/25465975/126842708-2edbc6d7-9b5b-44c7-85b4-db0bf1b97f07.png)

I cant for the love of me find which highlight is for that little grey part between tabs,
Also the offset for Nvimtree seems to be off as you see on the screenshot

**Comment by akinsho** [comment]
@ChrisTsou that should be the separator shading or something similar. I'm on mobile so can't give any detail if you check through the docs you'll find a matching style.

Regarding the offset that's how vim shades the separator between windows and also depends on the character you use for it. It's not something this plugin can solve for a user. They need to find a left aligned or right aligned vert split character on their own and that should make things appear to line up better

**Comment by ChrisTsou** [comment]
Yep found it, it was separator_selected and seperator_visible set the fg only.
I also figured the the font i was using had completely messed up boxing characters hence the messed up offset,
