### ISSUE TITLE
How to change highlights from .vimrc?

### ISSUE THREAD

**Issue by reportaman** [akinsho/nvim-bufferline.lua#163]
Hi, I do not have a lua based setup and its not clear how to correctly apply highlights.

Here's the sequence of statements I have in my .vimrc:

1. Load this plugin with vim-plug
2. After plug#end(), I have this:
```
if has('nvim')
    lua require'bufferline'.setup{
                \     fill = {
                \     guifg = '#ffffff',
                \     guibg = '#000000',
                \     },
                \ background = {
                \     guifg = '#ffffff',
                \     guibg = '#000000'
                \     },
                \ }
endif
```

These changes are not applied to nvim buffer line. I intend to change the background color of the entire tabline. Also, I don't want to affect the other highlights calculated by your plugin.

**Comment by akinsho** [comment]
@reportaman you can use a lua heredoc to write plain lua insidea vimscript, I'm on mobile so can't easily show an example. It's in the nvim docs though :h heredoc. 

In your case it also looks like the highlights are not correctly nested in a highlights table i.e. they should not be top level

**Comment by akinsho** [comment]
@reportaman can I close this now?

**Comment by reportaman** [comment]
@akinsho Thanks for asking :) I didn't get a chance to try it yet. Lemme get back in an hour.

**Comment by akinsho** [comment]
Gonna close this out since it's really more about using lua in vimscript rather than an issue with this plugin. This can be achieved by just doing something like
```vim
lua << EOF
require'bufferline'.setup {
  highlights = {
    ...
  }
}
EOF
```
