### ISSUE TITLE
How can i restore old view (buffer not tab)

### ISSUE THREAD

**Issue by ayoubelmhamdi** [akinsho/nvim-bufferline.lua#174]
I'm conflict between tab and buffer
I'm family with old tab and windows
if i choose open like windows/buffers i do: 
```bash
nvim foo.txt bar.txt
```
if i choose open like tabs i do: 
```bash
nvim foo.txt bar.txt -p
```
also how can i toggel view history tab?

**Comment by akinsho** [comment]
@ayoubelmhamdi I'm sorry, but I don't understand at all what you mean. If you open nvim with just the files, that will show two buffers. If you open `nvim -p` there will still be 2 buffers but also 2 tabs 🤷🏿‍♂️ . To be clear, this plugin show/focuses on *buffers*

**Comment by ayoubelmhamdi** [comment]
if i use `nvim -p` i want tow show tow tabs , but if i use only `nvim` i want to show one tab 
can i do that in future

**Comment by akinsho** [comment]
@ayoubelmhamdi I think this issue is probably due to a misunderstanding of this plugin. To be clear, this plugin shows *buffers* mainly *not* tabs.

**Comment by ayoubelmhamdi** [comment]
@Akianonymus  :yah it's also named `/nvim-bufferline.lua` , and very cool for buffer and fast, but i'm still want `tabline` with `lua` with old view (^_^)

**Comment by akinsho** [comment]
@ayoubelmhamdi that is not something this plugin provides 🤷🏿‍♂️ if you are willing to work on this and create a pull request I'd be happy to help guide it, but otherwise I'm going to close this out since it's something this plugin can do currently and something I don't personally intend to provide.
