### ISSUE TITLE
[Feature Request] Add buttons to bufferline 

### ISSUE THREAD

**Issue by siduck76** [akinsho/nvim-bufferline.lua#183]
![image](https://user-images.githubusercontent.com/59060246/129329318-2601fdb4-a766-488f-b1a6-8d0a0a6c14c7.png)

Is there any config to add multiple buttons here (on the right) , similar to the close button?

**Comment by siduck76** [comment]
I wanted to add another button which executes certain cmd commands on being clicked

**Comment by akinsho** [comment]
@siduck76 you can create a `custom_area` in your config see https://github.com/akinsho/nvim-bufferline.lua#custom-area and then add whatever you want into that space.

**Comment by siduck76** [comment]
@akinsho I added some icons here 
![image](https://user-images.githubusercontent.com/59060246/129337067-4cc85858-1fae-402c-961a-5f430fcbe469.png)

any way I could show the custom area to the left of the close_button? I want the close_button as the last icon

**Comment by akinsho** [comment]
Nope sorry, the custom area is rendered after the close button. It supposed to be after the bufferline content and is much messier and complicated if it inside it.

**Comment by siduck76** [comment]
> Nope sorry, the custom area is rendered after the close button. It supposed to be after the bufferline content and is much messier and complicated if it inside it.

oh , btw can we make these buttons clickable? I want to execute certain cmds when a button is clicked

**Comment by siduck76** [comment]
> Nope sorry, the custom area is rendered after the close button. It supposed to be after the bufferline content and is much messier and complicated if it inside it.

no worries! I disabled the close icon and added another button for the close icon in the custom area 

![image](https://user-images.githubusercontent.com/59060246/129339247-237d76bb-2bc5-4e0c-a66d-a6468f99f729.png)

**Comment by siduck76** [comment]
if clicking these was possible , then it would be great :(

**Comment by akinsho** [comment]
@siduck76 you can already make them clickable yourself
e.g.
```
%@FunctionName@<icon-here>%X
```

Then in vimscript
```vim
function FunctionName(arg1, arg2, arg3, arg4)
  " Do logic
endfunction
```

See `:help statusline` under the `@` section

> 	@ N   For 'tabline': start of execute function label. Use %X or %T to 
	      end the label, e.g.: %10@SwitchBuffer@foo.c%X.  Clicking this 
	      label runs specified function: in the example when clicking once 
	      using left mouse button on "foo.c" "SwitchBuffer(10, 1, 'l', 
	      '    ')" expression will be run.  Function receives the 
	      following arguments in order:
	      1. minwid field value or zero if no N was specified
	      2. number of mouse clicks to detect multiple clicks
	      3. mouse button used: "l", "r" or "m" for left, right or middle 
	         button respectively; one should not rely on third argument 
	         being only "l", "r" or "m": any other non-empty string value 
	         that contains only ASCII lower case letters may be expected 
	         for other mouse buttons
	      4. modifiers pressed: string which contains "s" if shift 
	         modifier was pressed, "c" for control, "a" for alt and "m" 
	         for meta; currently if modifier is not pressed string 
	         contains space instead, but one should not rely on presence 
	         of spaces or specific order of modifiers: use |stridx()| to 
	         test whether some modifier is present; string is guaranteed 
	         to contain only ASCII letters and spaces, one letter per 
	         modifier; "?" modifier may also be present, but its presence 
	         is a bug that denotes that new mouse button recognition was 
	         added without modifying code that reacts on mouse clicks on 
	         this label.
	      Note: to test whether your version of Neovim contains this 
	            feature use `has('tablineat')`.

**Comment by siduck76** [comment]
@akinsho could we use lua function for it ?

**Comment by akinsho** [comment]
@siduck76 no that won't work. The tabline click feature was added long before the nvim lua integration. It expects a `FuncRef` i.e. a reference to a `viml` function. It is currently not possible to pass a reference using `v:lua.MyFunc` that will error. This is the only reason bufferline still has some vimscript code. I suggest you use a 
```lua
vim.cmd[[
 function MyFunc()
  " do stuff
 endfunction
]]
```

**Comment by siduck76** [comment]
@akinsho I tried that and here's my icon : 

![image](https://user-images.githubusercontent.com/59060246/129345567-317377ed-9987-41a0-8a8e-3f9a23595425.png)


My funciton : 
![image](https://user-images.githubusercontent.com/59060246/129345635-c2db2072-4a45-4279-adee-49b93a2bbd5d.png)


I get this error : 
![image](https://user-images.githubusercontent.com/59060246/129345591-86d3e0a6-0475-4089-a13f-e1534070736c.png)

**Comment by akinsho** [comment]
@siduck76 you should read the documentation I shared about how the `tablineat` functions work, they receive 3 or 4 arguments and in viml you always have to specify the correct number of arguments whereas your function does not declare any arguments so you get an error.

**Comment by siduck76** [comment]
@akinsho thanks for all the help! It works . have a nice day :heart:

**Comment by gacallea** [comment]
hi @akinsho :)

sorry to bother you for this directly, I didn't want to open a separate issue and there is no Discussion functionality on the repo. I have a similar goal. For each buffer instead of the custom area. Is it possible to add those buttons to appear on the right of each buffer and add functions to them for a specific filetype only?

<img width="732" alt="Screenshot 2024-01-24 at 9 48 07 AM" src="https://github.com/LazyVim/LazyVim/assets/3269984/d5da773f-d1da-494a-bdbf-fd8f56c65e6a">

I looked at the code if it was somehow possible to reuse the diagnostic code and have those instead, but I haven't found a way.

Please and thank you

**Comment by gacallea** [comment]
After searching the repo and realized is probably ok, I ended up opening a separate issue.
