### ISSUE TITLE
FeatureRequesst:  Buffer picking mode 

### ISSUE THREAD

**Issue by glepnir** [akinsho/nvim-bufferline.lua#24]
check barbar.nvim it has buffer pick mode the behavior like easymotion , can jump to buffer by letters. code in here.
https://github.com/romgrk/barbar.nvim/blob/master/plugin/bufferline.vim#L478

preview in here https://github.com/romgrk/barbar.nvim#jump-to-buffer

**Comment by akinsho** [comment]
@glepnir please have a look at the README I have already, implemented this. It's not exactly the same so if there are any improvements you would like please consider a PR

**Comment by glepnir** [comment]
@akinsho  Oh. I missed it..you are right.
