### ISSUE TITLE
Error executing lua [string ":lua" ]:1: module 'bufferline' not found

### ISSUE THREAD

**Issue by s1n7ax** [akinsho/nvim-bufferline.lua#25]
**Error:**
`Error executing lua [string ":lua" ]:1: module 'bufferline' not found`

**Solution:**
I'm using [vim-plug](https://github.com/junegunn/vim-plug) to install bufferline. previously I had the setup call within `plug#begin` and `plug#end` blocks. call `lua require'bufferline'.setup()` after `plug#end` fixed the issue

```vim
call plug#begin()
Plug 'akinsho/nvim-bufferline.lua'
call plug#end()
set termguicolors
lua require'bufferline'.setup()
```

**Comment by s1n7ax** [comment]
Just wanted to post a solution

**Comment by SendohAkira** [comment]
You should execute PackerInstall in your nvim
