### ISSUE TITLE
How to skip some buffers from getting listed?

### ISSUE THREAD

**Issue by tami5** [akinsho/nvim-bufferline.lua#26]
Hi @akinsho, hope you're doing well. I'm starting to use vim-dispatch to connect to servers, but I noticed that when I do so a new buffer get listed.

Is there a way to skip those buffer from getting listed? thanks

**Comment by akinsho** [comment]
@tami5 I think the best way to do this is by setting those buffers to be `nobuflisted` e.g.
if you know what the filetype is or buffer name you can do
`autocmd FileType <thing> setlocal nobuflisted` or `autocmd BufEnter *.myfile setlocal nobuflisted` which means they won't be listed and so won't show up in the bufferline.

**Comment by tami5** [comment]
Amazing, thanks so much @akinsho .
