### ISSUE TITLE
bufferline colors

### ISSUE THREAD

**Issue by Gako358** [akinsho/nvim-bufferline.lua#339]
Just as you closed my last issue i was writing more, my bad for being to fast on the conclusions...
However,
![bar](https://user-images.githubusercontent.com/42249650/158228975-36889531-4f3e-428d-b891-f1a42eee435c.png)

As you can see, the fill works on the right side, but since I am using slant separator style, the background in between the "slants" are not changed with fill, tried pretty much all in doc but cannot find how to fill that background.

Any idea

**Comment by akinsho** [comment]
@Gako358 This information is in the help docs. You might have to try quite a few different highlight groups but it should be in there. I don't know what they are off the top of my head and I would have to check it just the same as you. They are definitely there though. Also can you move this comment to the old issue and I will reopen that one and close this one? I'm having a hard time managing all the issues being raised
