### ISSUE TITLE
when instaling bufferline with plug I cannot open checkhealth

### ISSUE THREAD

**Issue by gaetan-puleo** [akinsho/nvim-bufferline.lua#34]
I have installed bufferline and when I try to do a `:checkhealth`, neovim is stuck for ever.

If I remove bufferline `:checkhealth` is working

I have NVIM 0.5.0-dev

**Comment by akinsho** [comment]
@gaetan-puleo thanks for trying out the plugin. That sounds like a *very* strange but, nothing this plugin does should affect `:checkhealth` in any way. I've just run it locally on a nightly build and it runs without any issue. Can you share a minimal `init.vim` that reproduces this issue

**Comment by gaetan-puleo** [comment]
@akinsho here a minimal `init.vim`
I agree this is so strange!
```
call plug#begin('~/.config/nvim/plugged')
"  nvim bufferline
Plug 'akinsho/nvim-bufferline.lua'
call plug#end()

lua <<EOF
require('bufferline').setup({
    separator_style = "table",
    show_buffer_close_icons = true,
    view = "multiwindow",
  })
EOF
```

**Comment by gaetan-puleo** [comment]
Now nvim is stuck I cannot write any command and I cannot change the mode or write anything 
![Uploading Screenshot from 2020-12-06 23-34-15.png…]()
I am on Ubuntu 20.04, my terminal is kitty and I use zsh if it can help 

Sorry for my poor English

**Comment by akinsho** [comment]
@gaetan-puleo just tried it and `checkhealth` still works for me although there are quite a few things wrong with the config. Firstly the object inside the setup should be
```lua
options = { -- <--- This is missing
  separator_style = -- etc
}

-- Secondly there is no separator style called `table` you can use `slant` or pass in a *table* ie. a
-- lua data structure e.g. {"|", "|"}
```

**Comment by gaetan-puleo** [comment]
I just updated the `init.vim` to

```
call plug#begin('~/.config/nvim/plugged')
" " nvim bufferline
Plug 'akinsho/nvim-bufferline.lua'
call plug#end()

lua <<EOF
require('bufferline').setup({
    options = {
        separator_style = "slant",
        show_buffer_close_icons = true,
        view = "multiwindow",
    }
  })
EOF
```
`checkhealth` is working now

**Comment by gaetan-puleo** [comment]
I can close the issue now. thanks again

**Comment by carlitux** [comment]
I am having this issue with all setup

**Comment by akinsho** [comment]
@carlitux I'm not sure I understand what issue you are facing? Can you describe what exactly you're seeing and how I can reproduce it to test. The issue mentioned here was about the wrong configuration.

**Comment by carlitux** [comment]
I had this setup and do not work

```lua
local api = vim.api
local cmd = vim.cmd
local fn = vim.fn
local luv = vim.loop
local g = vim.g

local packer_path = luv.os_homedir() .. "/.local/share/nvim/site/pack/packer/opt/packer.nvim"

if fn.filereadable(packer_path .. "/README.md") == 0 then
  cmd [[echohl WarningMsg]]
  cmd [[echom "Installing dein plugin manager, please wait"]]
  cmd([[!git clone https://github.com/wbthomason/packer.nvim ]] .. packer_path)
  cmd [[echohl None]]
end

cmd [[packadd packer.nvim]]

local packer = require("packer")

packer.startup(
  function()
    packer.use({"wbthomason/packer.nvim", opt = true})
    packer.use(
      {
        "Akin909/nvim-bufferline.lua",
        config = function()
          require [[bufferline]].setup({
            options = {
              view = "multiwindow",
              numbers = "ordinal",
              number_style = "superscript",
              mappings = true,
              separator_style = "thin"
            }
          })
        end
      }
    )
  end
)
```

If I current buffer is an empty one neovim freezes

![Screenshot from 2021-01-09 17-17-12](https://user-images.githubusercontent.com/40538/104108890-df52fb80-529e-11eb-9647-61d4b548b880.png)

But if is into buffer loaded from file works

![Screenshot from 2021-01-09 17-19-00](https://user-images.githubusercontent.com/40538/104108902-f09c0800-529e-11eb-9f85-cb81b07565d7.png)

**Comment by akinsho** [comment]
I haven't really added any changes in a few weeks, is this a new problem? If you remove just this plugin is this issue resolved?

**Comment by carlitux** [comment]
I just noticed, I had the issues many times with Greeper but today also get noticed that with healthcheck has the same issue.

I had to search for the plugin that has the issue.

**Comment by akinsho** [comment]
@carlitux I use those plugin all the time with empty buffers and it doesn't freeze nvim for me. I'll test it with your config and see what happens. Also does it relate to checkhealth?

**Comment by hungrybirder** [comment]
> I had this setup and do not work
> 
> ```lua
> local api = vim.api
> local cmd = vim.cmd
> local fn = vim.fn
> local luv = vim.loop
> local g = vim.g
> 
> local packer_path = luv.os_homedir() .. "/.local/share/nvim/site/pack/packer/opt/packer.nvim"
> 
> if fn.filereadable(packer_path .. "/README.md") == 0 then
>   cmd [[echohl WarningMsg]]
>   cmd [[echom "Installing dein plugin manager, please wait"]]
>   cmd([[!git clone https://github.com/wbthomason/packer.nvim ]] .. packer_path)
>   cmd [[echohl None]]
> end
> 
> cmd [[packadd packer.nvim]]
> 
> local packer = require("packer")
> 
> packer.startup(
>   function()
>     packer.use({"wbthomason/packer.nvim", opt = true})
>     packer.use(
>       {
>         "Akin909/nvim-bufferline.lua",
>         config = function()
>           require [[bufferline]].setup({
>             options = {
>               view = "multiwindow",
>               numbers = "ordinal",
>               number_style = "superscript",
>               mappings = true,
>               separator_style = "thin"
>             }
>           })
>         end
>       }
>     )
>   end
> )
> ```
> 
> If current buffer is an empty one neovim freezes
> 
> ![Screenshot from 2021-01-09 17-17-12](https://user-images.githubusercontent.com/40538/104108890-df52fb80-529e-11eb-9647-61d4b548b880.png)
> 
> But if it is into buffer loaded from file works
> 
> ![Screenshot from 2021-01-09 17-19-00](https://user-images.githubusercontent.com/40538/104108902-f09c0800-529e-11eb-9f85-cb81b07565d7.png)
> 
> EDITED.
> 
> Also `:GrepperRg searchtext` has the same issue with the same steps

I got the same problem.

**Comment by carlitux** [comment]
> @carlitux I use those plugin all the time with empty buffers and it doesn't freeze nvim for me. I'll test it with your config and see what happens. Also does it relate to checkhealth?

I think it is related when a plugin creates a new window/tab that requires bufferline refresh the UI... just assuming I don't know how to test

**Comment by cooper-anderson** [comment]
I have been running to this same problem of `:checkhealth` stalling nvim forever. It has also happened in a few other cases as well, such as loading Telescope. But I have not been able to narrow it down to being a nvim-bufferline problem.

**Comment by akinsho** [comment]
@carlitux I've just tested out your config using `:checkhealth` and I can't reproduce this error. I need more specific information and how to reproduce it to dig in, and as was the case in the original issue here I don't really know why or how this plugin would block `:checkhealth`
