### ISSUE TITLE
"[nvim-bufferline]  is not a valid highlight group"

### ISSUE THREAD

**Issue by sheriferson** [akinsho/nvim-bufferline.lua#37]
(sorry, published the issue too early with a blank description)

I tried to modify the color of the tab bar at the top using the instructions in the README with small modification. Here's my entire nvim-bufferline section from `init.nvim`

```
lua require'bufferline'.setup {
            \ options = {
            \   show_buffer_close_icons = false,
            \   max_name_length = 40
            \ },
            \ highlights = {
            \   fill = {
            \     guifg = 'black',
            \     guibg = '#b2b2b2'
            \   };
            \ },
            \ }
```

The configuration works, the colors do change, but I get a "<blank> is not a valid highlight group" error on startup.

<img width="663" alt="Screen Shot 2020-12-26 at 4 51 20 PM" src="https://user-images.githubusercontent.com/3160968/103161706-a85af100-479a-11eb-84e1-efb8d09af26b.png">

I assume I'm missing something really obvious but I'm not sure what it is. I'd appreciate any tips.

**Comment by akinsho** [comment]
@sheriferson I don't think your config is correct, I think the lua code should be in a `heredoc` i.e. ```vim
lua << EOF
require'bufferline'setup {
 -- code goes here
}
```

**Comment by sheriferson** [comment]
Thanks for the tip, I tried modifying it to this (removed `options` to make things simpler):

```vim
lua << EOF
require'bufferline'.setup {
    highlights = {
        fill = {
            guifg = 'black',
            guibg = '#b2b2b2'
        }
    }
}
EOF
```

still getting the same warning.

**Comment by akinsho** [comment]
@sheriferson you're right there was a bug in the code, thanks for trying again. I've pushed a fix now which should have resolved the issue. Lemme know if that works for you now

**Comment by sheriferson** [comment]
@akinsho 👌🏽 Perfect, no more warning. Thanks for the quick bug fix.
