### ISSUE TITLE
[Bug]: 过滤buffer怎么过滤掉jdtls启动debug后产生的buffer？

### ISSUE THREAD

**Issue by xYx-c** [akinsho/nvim-bufferline.lua#388]
custom_filter = function(buf_number, _)
                if vim.fn.bufname(buf_number) ~= "<java>" then
                    return true
                end
            end,

### What happened?
<img width="516" alt="image" src="https://user-images.githubusercontent.com/57053484/164246001-c73c4459-e055-41cf-bc9c-436449625466.png">

222  aR  "term://~/hyt//7392:/usr/local/opt/openjdk@8/bin/java" line 0

### What did you expect to happen?

可以过滤掉启动debug的buffer吗？

### Additional Information

...

**Comment by akinsho** [comment]
@yil3 unfortunately, I don't speak ?mandarin? I'm not sure what the question is but I guess you are trying to filter out java files. That check won't work because it tries to match directly against a string `<java>` which does not exist. You should do something like
```lua
if vim.api.nvim_buf_get_name(buf_number):match('java') ~= nil then
	return true
end
```

**Comment by yil3** [comment]
> or if you want a direct match then `buf_get_name(buf_number) ~= 'java'` don't add `<`, `>` to the match

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/57053484/164252401-7e0975ba-6134-4905-804a-d8c1d9c4e647.png">
When jdtls starts debug, it produces a buffer, which prints the log. How should I filter it?
<img width="718" alt="image" src="https://user-images.githubusercontent.com/57053484/164252548-dbe452f6-4930-41a3-8812-53357c9a177a.png">

**Comment by akinsho** [comment]
@yil3 You just need to find the correct pattern to match on, which could take some work on your side. I don't believe this is a bug though, since it works fine for me and other users. You might want to do something like 
```lua
if vim.fn.expand(string.format('%d:t')) == 'java' then
	return false
else
	return true
end
```
Please try and figure out the correct pattern or strategy on your side, unfortunately I don't have the time at the moment to help implement each users specific preferred config.

**Comment by akinsho** [comment]
Can this be closed now?
