### ISSUE TITLE
Highlight names from theme do not seem to be getting used

### ISSUE THREAD

**Issue by medwatt** [akinsho/nvim-bufferline.lua#43]
I am trying to do some tweaks to get the highlighting right and I don't want to hard code the colour values. Instead I want to derive the colours from the theme that I am using. For example, these are some highlight groups in my theme file:

```vim
" call s:hi(item, fg, bg, cterm, gui)

call s:hi('Normal' , 249 , s:bg , 'None' , 'None')
call s:hi('Cursor' , 235 , 178  , 'bold' , 'bold')
``` 

In the config file for the plugin, I set the colours as such:

```vim
buffer_selected = {
            guifg = normal_fg,
           guibg = cursor_bg,
            gui = "bold,italic"
        },
```
This doesn't seem to have any effect. The only way at the moment to get the colours to change is by hard coding the values. Can you please clarify how exactly one can derive the colours from the theme ?

**Comment by akinsho** [comment]
@medwatt thanks for trying out the plugin.

From what you describe I'm definitely missing something in your example where do you create the `cursor_bg` variables in lua.

If you want to use some colour from your colorscheme you have to get there value as a lua variable and use it in the table.

```
local my_color = get_my_color('Normal')

-- in buffer line config

fill = {
  guifg = my_color
}
```

Can you paste a snippet of how you actually have this configured?

**Comment by medwatt** [comment]
Thanks for the reply. Here is a snippet of my config for this plugin in my `init.vim`.

```lua
require'bufferline'.setup{
    options = {
        numbers = "none",
        max_name_length = 10,
        max_prefix_length = 10,
        tab_size = 10,
    },
    highlights = {
        buffer_selected = {
            guifg = '#f0f0f0',
            gui = "bold,italic"
        },
        fill = {
            guibg = '#292b2e',
        },
        tab_close = {
            guibg = '#292b2e',
        },
    };
}
```

As you can see, I had to hard-code some of the colour values. Instead, I would prefer to use them from my colorscheme directly.

I looked into your code and found that you're calling colors like this:

```lua
local id = vim.fn.hlID("Error")
local my_color = vim.fn.synIDattr(id, "fg")
```

I added this code to my script and the colour indeed changed. You have a function called `get_hex()` that does this. I'm not that familiar with lua in neovim. How can I use the `get_hex()` in my config file ?

BTW, do you have a status line plugin that you recommend ?

**Comment by akinsho** [comment]
@medwatt that's good you found a solution 👍🏾.
 `get_hex` isn't exposed publicly so you can't use it in your dotfiles. Its only 2 lines to recreate so I don't think it needs to be exposed, also when nvim's API changes I'm likely to change the function so I'd rather not have users depending on internal functions like that one.

Re. Statusline plugins I don't use any plugins for it, I've heard about `expressline`, `galaxyline` and `lualine`. You can see if any of those works for you
