### ISSUE TITLE
Unable to configure highlighting

### ISSUE THREAD

**Issue by Shatur95** [akinsho/nvim-bufferline.lua#46]
Hi! I am trying to change the highlight settings and when copying any parameter and the documentation, I get the error:

```lua
vim.cmd('packadd nvim-bufferline.lua')

require'bufferline'.setup{
  highlights = {
    fill = {
      guifg = comment_fg,
      guibg = separator_background_color
    },
  };
}
```

```
Error detected while processing ColorScheme Autocommands for "*":
Failed setting BufferLineFill highlight, something isn't configured correctly
Vim(highlight):E411: highlight group not found: BufferLineFill
```

Am I doing something wrong? I have it installed in `opt` dir and my configuration in lua.

**Comment by akinsho** [comment]
@Shatur95 the colour variables in your example where are they defined? Have you extracted those colours somewhere. The examples in the docs aren't globals you need to get the colours your want to use yourself

**Comment by akinsho** [comment]
See #43 for reference since this appears to be the same issue. I will update the docs to make this clearer for people

**Comment by Shatur95** [comment]
Got it, thank you!

**Comment by Shatur95** [comment]
@akinsho, one question. I noticed that you have colored icons in your screenshot. In my case, all icons are in grayscale. How can I make the icons color like in the screenshot.

**Comment by akinsho** [comment]
@Shatur95 do you have nvim webdev icons installed? That's where the highlights come from?

**Comment by Shatur95** [comment]
@akinsho, Yes, I have `nvim-web-devicons` that loaded before `nvim-bufferline.lua`.

**Comment by akinsho** [comment]
@Shatur95 this might depend on your setup, having devicons should be enough. If you try with a minimal init.vim or init.lua i.e no other config no autocommands etc does it work? I get icon colours without issue

**Comment by Shatur95** [comment]
Thanks. I thought I was missing some option.
The problem was in used colorscheme.

**Comment by Shatur95** [comment]
@akinsho, hmm, I was wrong, in Telescope the icons are colored if nvim-bufferline.lua is not loaded. What icon theme are you using?

**Comment by akinsho** [comment]
@Shatur95 there isn't a theme for the icons, `nvim-web-devicons` returns a highlight for each icon which we simply apply in the bufferline, so it isn't related to my colorscheme at all. Have you tried with a minimal init.vim/lua i.e. no other config or settings except loading this plugin?

something like `nvim -u <file-beneath>`
```lua
vim.cmd [[set termguicolors]]
vim.cmd [[packadd bufferline]]
require('bufferline').setup{}
```

you can also check the value of `verbose highlight BufferlineDevIcon{Ft}`

**Comment by Shatur95** [comment]
@akinsho, yes, I know. I mean what colorscheme do you use?

> Have you tried with a minimal init.vim/lua i.e. no other config or settings except loading this plugin?

Yes, that's exactly what I tried. I will try to explain in more detail. If I disable the plugin with a colorscheme, then the icons have a color. If I disable `nvim-bufferline.lua`, and enable theme back - icons have colors too.

**Comment by Shatur95** [comment]
Also if I load `nvim-web-devicons` after `nvim-bufferline.lua`, then bufferline will have no icons at all (expected result), but all other plugins (that loaded after `nvim-web-devicons`) will have **colored** icons.

**Comment by Shatur95** [comment]
`verbose highlight BufferlineDevIcon{Ft}`

Hm... It says that not such group...

**Comment by akinsho** [comment]
@Shatur95 sorry I don't think I follow what isn't working anymore
> but all other plugins (that loaded after nvim-web-devicons) will have colored icons. So I think that nvim-bufferline.lua somehow prevents icons colorization.

Do you mean that other plugins that use `nvim-web-devicons` aren't showing highlights *because* of bufferline?
I use `rakr/vim-one` as my colorscheme but I'm not sure that that is related tbh

So the specifics of what this plugin does is that for each filetype it *copies* the `fg` highlight of the icon and then creates a *new* bufferline highlight the name should be `BufferLineDevIconLua` for example note the `BufferLine` is written like that. It doesn't overwrite or deactivate any of the actual highlights that devicons produces.

**Comment by Shatur95** [comment]
> Do you mean that other plugins that use nvim-web-devicons aren't showing highlights because of bufferline?

Yes, if I disable `nvim-bufferline.lua` - the icons works.

>  I use rakr/vim-one as my colorscheme but I'm not sure that that is related tbh

You are right. I tried it, but the same issue with the same colorscheme too.

**Comment by Shatur95** [comment]
This line causes the issue:

https://github.com/akinsho/nvim-bufferline.lua/blob/c5b0800bfeb16d916b12602a4d8aee6d9e06d712/lua/bufferline/buffers.lua#L1

If I comment it out (with other related to icons stuff in this file) - I have icons at least in other plugins.
If I left these lines uncommented and comment out only other icons-related stuff in this file - the icons still have no colors. So, I suspec that the issue in line 1-4.

**Comment by akinsho** [comment]
@Shatur95 that's pretty strange, I don't see the same issue and I use `Telescope` as well what plugins specifically aren't working? I think somewhere else something is going wrong since if you look at the implementation of [`setup`](https://github.com/kyazdani42/nvim-web-devicons/blob/aaffb87b5a640d15a566d9af9e74baafcf9ec016/lua/nvim-web-devicons.lua#L839) at worst calling that function again just re-applies the highlights. If I remove this line it will almost certainly break for other users.

One thing you could try is adding `require'nvim-web-devicons'.has_loaded()` which is an api that was added to that plugin a while ago so the above check would become `lua_devicons_loaded
```lua
 if lua_devicons_loaded and not webdev_icons.has_loaded() then 
   webdev_icons.setup() 
 end 
```
That shouldn't break things for other people, and I'd accept a PR with that change (after testing to make sure it doesn't break) I won't be free for a little while but really I'm quite confused about why that is necessary at all since calling setup should just re-apply the icon highlights so I think some other plugin or custom function is doing something strange

**Comment by Shatur95** [comment]
>  If I remove this line it will almost certainly break for other users.

Of course, we shouldn't do this. But the information provided will help us to figure out what the problem is :)

> that's pretty strange, I don't see the same issue and I use Telescope as well what plugins specifically aren't working?

Telescope, it also displays icons without color for me (and have colors without that check).

> One thing you could try is adding require'nvim-web-devicons'.has_loaded() which is an api that was added to that plugin a while ago so the above check would become

I tried this, but the result hasn't changed :(

**Comment by akinsho** [comment]
@Shatur95 maybe try reordering when telescope is loaded. If it's before buffer line then try after and vice versa. I'll try and reproduce it when I get a chance

**Comment by Shatur95** [comment]
@akinsho, yes, I tried it but it doesn't help. I am not using a package manager, this may be the problem. [Here](https://github.com/Shatur95/neovim-config) is my configuration.

**Comment by akinsho** [comment]
Hmm tbh I'm not an expert in the direct usage of vim packages, there's a lot of confusing stuff about ordering etc. which I've seen crop up before. OOI can you try a minimal version using something like `vim-plug`, reason being I'm wondering if the order and timings of the `packadd` commands is a factor. Also beforehand can you also try using `packadd!` with a `!` to load bufferline and telescope. It seems that using it with the `!` is supposed to be useful in `.vimrc` according to `:h packadd`

**Comment by Shatur95** [comment]
Hm... I think I found the issue. It looks like manual initialization of `nvim-web-devicons` is redunant. Could you check me PR?

> Also beforehand can you also try using packadd! with a ! to load bufferline and telescope. It seems that using it with the ! is supposed to be useful in .vimrc according to :h packadd

Thanks, I just forgot about the `!` after switching to lua. This must be used in my configuration, but I checked - it does not affect the problem.
