### ISSUE TITLE
[Bug]: Left Trunc Marker and clickable area are offset to one another

### ISSUE THREAD

**Issue by CodedCraft** [akinsho/nvim-bufferline.lua#478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Clicking on the left trunk marker doesn't work, instead I have to click in the empty space between the left trunk marker and the first visible buffer as shown in the picture:
![Screenshot 2022-07-13 at 14 40 22](https://user-images.githubusercontent.com/58528488/178737150-1ceefc03-15fd-4b1c-bdbf-1c0f0fbfc5e7.jpg)

I am not sure if this is a bug or if something is misconfigured on my system. If it's not replicable I will do more extensive digging on my system with a minimal NeoVim config etc.

### What did you expect to happen?

Same behaviour as on the right side: clicking on the right trunc marker works properly.

### Config

```
local ok, bufferline = pcall(require, "bufferline")

if not ok then
   return
end

bufferline.setup({
	options = {
		tab_size = 24,
        show_close_icon = false,
        show_tab_indicators = true,
        left_trunc_marker = '',
        separator_style = "thin", --  slant, padded slant, thick, thin, { 'any', 'any' }
          always_show_bufferline = false,
        offsets = {
            {
                filetype = "neo-tree",
                text = "",
                padding = 0,
                text_align = "center",
                highlight = "BufferlineBackground",
            },
        },
		diagnostics = "nvim_lsp",
		diagnostics_update_in_insert = false,
	},
})

```

### Additional Information

MacOS 12.4
Kitty Terminal w/ Tmux
(also tried Alacritty with the same result)

**Comment by akinsho** [comment]
Hi @philip1987,

I'm not sure, I understand the bug, actually. The offset markers aren't clickable at all, they aren't supposed to be. They are just visual indicators that there are x number of buffer off-screen

**Comment by philip1987** [comment]
@akinsho Now I feel dumb, sorry to have wasted your time. So it turns out that what I was actually clicking was the first visible tab or the empty space after the last visible tab and not the trunc indicators. Thank you for your great plugin and all your contributions to the neovim community.
