### ISSUE TITLE
Bug: Icon highlight always has darker background

### ISSUE THREAD

**Issue by Luxed** [akinsho/nvim-bufferline.lua#50]
Here's an example:
![image](https://user-images.githubusercontent.com/10234894/107307851-84572480-6a55-11eb-8cc0-aefedbdac378.png)

EDIT: so this might be because of [my theme](https://github.com/Luxed/ayu-vim)

**Comment by Luxed** [comment]
I'm sorry for this. It was 100% my fault. My config was in the wrong order, so the background would be taken from the "dark" style instead of the "mirage" style.
Which brings me to another issue, if I change colorscheme, everything updates _but_ the background of the icon. Here's an example of simply changing the background from dark to light:
![image](https://user-images.githubusercontent.com/10234894/107313512-a86c3300-6a60-11eb-9b33-7d3cb18f5f60.png)

**Comment by akinsho** [comment]
@Luxed, the icon highlight issue has been a known bug for a little while I wasn't able to find a solution for it. Although I just pushed a fix this morning, the colors should now update when you change theme

**Comment by Luxed** [comment]
Well, thanks to your fix, the issue is resolved for me. Thank you very much!
