### ISSUE TITLE
How can i set the numbers on the right not to show?

### ISSUE THREAD

**Issue by hrqmonteiro** [akinsho/nvim-bufferline.lua#57]
![2021-03-11_14-19](https://user-images.githubusercontent.com/17055027/110827688-1761c500-8275-11eb-9ba3-588f32a598bc.png)

I tried setting:

```
require"bufferline".setup {
  options = {
    view = "multiwindow",
    numbers = 'none',
    number_style = '',
  }
}
```

EDIT: the `separator_style` won't work as well, i tried setting it like this right now:

![2021-03-11_14-30](https://user-images.githubusercontent.com/17055027/110829022-6f4cfb80-8276-11eb-9e34-7d9b62b4b84f.png)

And the tab styling remains the same, the default one.

**Comment by akinsho** [comment]
@hrqmonteiro do you mean the tab indicators showing `1` and `2`? if so I haven't built a way to turn those off I rely on them a lot and have never been asked before to make them configurable so they currently aren't. It's not a lot of work to add but I'm pretty busy at the moment.

Alternatively would be happy to show you where you need to look to make it configurable and make a PR.

**Comment by akinsho** [comment]
I just took a sec to quickly add it the options to hide it is now `show_tab_indicators = false` in the options table if you want to hide them

**Comment by hrqmonteiro** [comment]
Thanks, man! That's perfect!
