### ISSUE TITLE
Buffers not working as expected

### ISSUE THREAD

**Issue by samyak-jain** [akinsho/nvim-bufferline.lua#60]
It seems that the way bufferline handles buffers is not quite the same as how it normally works. 
When I use the mouse to close tabs, it works as expected. However, when I use ```:q``` to close the buffer, bufferline doesn't reflect that. When I use the mouse to close the tab, it doesn't look like it actually closes the buffer. Any idea if it's possible to sync bufferline with the acutal buffer list? Or am I configuring this wrong?

**Comment by akinsho** [comment]
@samyak-jain I'm not entirely sure what you are describing. `:q` will close a window not a buffer, `:bd` will close a buffer. from vim docs.
> :q[uit]			Quit the current window.  Quit Vim if this is the last
			window.  This fails when changes have been made and
			Vim refuses to |abandon| the current buffer, and when
			the last file in the argument list has not been
			edited.
			If there are other tab pages and quitting the last
			window in the current tab page the current tab page is
			closed |tab-page|.
			Triggers the |QuitPre| autocommand event.

Bufferline already does use the exact buffer list from vim but doesn't show any unloaded buffers. Which buffers are shown is more related to how vim handles things bufferline doesn't actually control how vim is showing or hiding buffers. It uses the `bd` command under the hood when you click to close a buffer

**Comment by samyak-jain** [comment]
Gotcha. Got myself confused. Thanks for clarifying.
