### ISSUE TITLE
Make close optional

### ISSUE THREAD

**Issue by samyak-jain** [akinsho/nvim-bufferline.lua#61]
We can currently choose to not have the close_icons for the individual tabs. However, as far as I can see, there is not way to opt out of having the close button on the far right. 
https://github.com/akinsho/nvim-bufferline.lua/blob/6f104eab57f0c7f1241e4ba0da12c9d1362f589f/lua/bufferline.lua#L543

**Comment by akinsho** [comment]
That option doesnt currently exist but wouldn't be too hard to implement, I'm fairly busy/stretched atm to add that in but if someone wanted to contribute a PR that implemented it in a toggle-able with the default being on then I'd be fine to merge that.

**Comment by samyak-jain** [comment]
I've made the PR #62. Let me know if this looks fine to you.

**Comment by samyak-jain** [comment]
Thanks for merging the PR. Works great!
