### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by akinsho** [akinsho/nvim-bufferline.lua#66]
![diagonal](https://user-images.githubusercontent.com/22454918/111992989-fec39b80-8b0d-11eb-851b-010641196a04.png)
![lsp_error](https://user-images.githubusercontent.com/22454918/111993085-1d299700-8b0e-11eb-96eb-c1c289e36b08.png)
![bufferline_with_numbers](https://user-images.githubusercontent.com/22454918/111993201-3d595600-8b0e-11eb-8944-387ed3bd25b4.png)
![bufferline_pick](https://user-images.githubusercontent.com/22454918/111993296-5bbf5180-8b0e-11eb-9ad9-fcf9619436fd.gif)
![duplicate_names](https://user-images.githubusercontent.com/22454918/111993343-6da0f480-8b0e-11eb-8d93-44019458d2c9.png)
![close_button](https://user-images.githubusercontent.com/22454918/111993390-7a254d00-8b0e-11eb-9951-43b4350f6a29.gif)
![re-order](https://user-images.githubusercontent.com/22454918/111993463-91643a80-8b0e-11eb-87f0-26acfe92c021.gif)

**Comment by akinsho** [comment]
![bufferline_pick](https://user-images.githubusercontent.com/22454918/111994691-f2404280-8b0f-11eb-9bc1-6664ccb93154.gif)

**Comment by akinsho** [comment]
![image](https://user-images.githubusercontent.com/22454918/113215394-b1180300-9272-11eb-9632-8a9f9aae99fa.png)

**Comment by jerrywang1981** [comment]
<img width="657" alt="Screen Shot 2021-04-02 at 10 58 12 AM" src="https://user-images.githubusercontent.com/8133242/113400253-159ea380-93d4-11eb-822c-974d728a6bcf.png">
<img width="636" alt="Screen Shot 2021-04-02 at 11 38 51 AM" src="https://user-images.githubusercontent.com/8133242/113400265-1a635780-93d4-11eb-8085-adc328385cb5.png">

**Comment by akinsho** [comment]
![image](https://user-images.githubusercontent.com/22454918/118525973-aa1c5580-b737-11eb-883c-a2c55b7af479.png)

**Comment by akinsho** [comment]
![image](https://user-images.githubusercontent.com/22454918/118527523-4d219f00-b739-11eb-889f-60fb06fd71bc.png)

**Comment by lcrockett** [comment]
![nvim-bufferline-conditional-lsp-indicator-current-00](https://user-images.githubusercontent.com/58056722/119390133-e5d19500-bccc-11eb-915d-f5d11f8e652c.jpeg)
![nvim-bufferline-conditional-lsp-indicator-visible-00](https://user-images.githubusercontent.com/58056722/119390136-e66a2b80-bccc-11eb-9a87-e622e3e20563.jpeg)

**Comment by akinsho** [comment]
<img width="1694" alt="Screenshot 2023-02-20 at 12 57 49" src="https://user-images.githubusercontent.com/22454918/220115787-0ba2264f-1cf5-4f18-a322-7c7cfa3d8f42.png">
