### ISSUE TITLE
show only tabs

### ISSUE THREAD

**Issue by roberbnd** [akinsho/nvim-bufferline.lua#68]
is it possible configure the plugin to show only tabs?
like `let g:airline#extensions#tabline#enabled = 1` in airline

**Comment by akinsho** [comment]
@roberbnd, no not really see #64. Basically the object of the plugin is to visualise buffers. It could be adapted to have a tabs only mode, but I don't plan on implementing it personally. If someone else put together a PR and it didn't disrupt the rest of the functionality of the plugin or cause too much complexity then I'd probably accept it.
