### ISSUE TITLE
Cannot style seperator background color when seperator_style = "slant" is configured

### ISSUE THREAD

**Issue by Racle** [akinsho/nvim-bufferline.lua#73]
I've added fill guibg color and it doesn't work while `seperator_style = "slant"`.
I also tried to set background and seperator styles with no success.
I try to get `#282828` as background color as it fits style much better than black background.

Preview:
![image](https://user-images.githubusercontent.com/759091/113666121-66095000-96b7-11eb-9fd9-d563e4065ad6.png)

As you can see, seperator backgrounds are black and not `#282828`. Right side has correct color applied. Background color changes when I switch to light theme, so there should be something that I could configure.

My current configuration: 
```lua
vim.o.termguicolors = true

require "bufferline".setup {
  highlights = {
        fill = {
            guibg = "#282828"
        },
    },
    options = {
        modified_icon = "●",
        left_trunc_marker = "",
        right_trunc_marker = "",
        max_name_length = 25,
        max_prefix_length = 25,
        enforce_regular_tabs = false,
        view = "multiwindow",
        show_buffer_close_icons = false,
        show_close_icon = false
        separator_style = "slant",
    }
}
```

**Comment by akinsho** [comment]
@Racle the correct highlight groups to colour the separators isn't `fill`, you will need to override the various `separator_*` mappings such as `separator_visible` etc

Here's an example I just tried. See `:h bufferline-lua-highlights` for a full list of available highlights
![image](https://user-images.githubusercontent.com/22454918/113672675-f5126a00-96af-11eb-8b39-ea0b888e4df9.png)

**Comment by Racle** [comment]
@akinsho thanks, I think I messed up when testing my configuration..

adding this works very well.
```lua 
highlights = {
  fill = {
      guibg = "#282828"
  },
  separator_selected = {
      guifg = "#282828"
  },
  separator_visible = {
      guifg = "#282828"
  },
  separator = {
      guifg = "#282828"
  },
},
```

Just noticed another small visual problem:
![image](https://user-images.githubusercontent.com/759091/113675646-40cf0e80-96c4-11eb-8ef4-79aab96f41b3.png)

I wonder if it is possbile to put something like 2 character wide empty space on left side? Or different guigb to first item... (unless there is left_trunc_marker visible). I might be asking little too much :)

**Comment by akinsho** [comment]
@Racle glad it worked. Regarding the signcolumn highlighting and shifting things. I think that would be a rabbit hole since the signcolumn in nvim is dynamic i.e. can resize from 0 - 9 characters wide, so this would mean having to redraw the statusline and adjust the padding whenever the statusline changed, not to mention having to add parsing for the option which has grown increasingly complex (but still doable).

It would also eat up space that could be used to fit in more information. I think in your case you could clear the signcolumn background colour if that doesn't bother you too much. `hi SignColumn guibg=NONE`

**Comment by Racle** [comment]
@akinsho yeah that's too much work just for minor thing (even tho I have that as fixed width now.) 

I'm probably just going to ignore that minor detail (and is less annoying than removing signcolumn bg). Otherwise bufferline works just fine :)
