### ISSUE TITLE
disable separator

### ISSUE THREAD

**Issue by alex-popov-tech** [akinsho/nvim-bufferline.lua#74]
hi again !
is there an ability to disable separators completely?
im trying to achieve minimal ui, and want to see just icon and name

**Comment by akinsho** [comment]
@alex-popov-tech 👋🏿 you can do this by setting the separator style to `separator_style = {"", ""}` I think this used to be/maybe still is in the README or docs somewhere.

**Comment by alex-popov-tech** [comment]
@akinsho tried, didnt work 
<img width="890" alt="image" src="https://user-images.githubusercontent.com/21224705/113706906-ddef6e80-96e7-11eb-8c44-a373e99d8ffe.png">

**Comment by alex-popov-tech** [comment]
(i mean that red bar)

**Comment by akinsho** [comment]
@alex-popov-tech ah that's not a separator it's an indicator, in bufferline terms. The separators are invisible in your screenshot. You can't entirely disable it but you can style it using `indicator_selected`, `indicator_visible` etc.

**Comment by alex-popov-tech** [comment]
yeah, but i cant make it transparent, right?

**Comment by akinsho** [comment]
@alex-popov-tech you should be able to just set it to the color of the background which is essentially the same thing. This makes it invisible.

![image](https://user-images.githubusercontent.com/22454918/113712284-d88d2680-96dd-11eb-8223-4416c52bc871.png)


```lua
highlights = {
  indicator = {
   guifg = {
	attribute = "bg",
    highlight = "Normal",
   }
  }
}
```

**Comment by alex-popov-tech** [comment]
didn't know about that ability !
thanks, much better now!
