### ISSUE TITLE
I've also changed the `group.matcher` argument to pass in less private/internal data

### ISSUE THREAD

**Issue by cazador481** [akinsho/nvim-bufferline.lua#744]
I've also changed the `group.matcher` argument to pass in less private/internal data
e.g.
```lua
options = {
  groups = {
  options = { toggle_hidden_on_enter = true },
  items = {

    {
      name = 'Dependencies',
      icon = '',
      matcher = function(buf) -- buf here is now only a subset of the full buffer object
		return vim.startswith(buf.path, vim.env.VIMRUNTIME)
	  end,
    },
}
```
The bufferline-groups example needs to be updated to match this change.

**Comment by akinsho** [comment]
@cazador481 can you please expand on what you are trying to say? why does this example need updating. The `path` field is still exposed

**Comment by cazador481** [comment]
Sorry, that was a horrible request.  I was trying to just add a comment to another bug.  And someone this was opened.  In the bufferline-groups help section.  The following example is shown
```lua
{
        name = "Docs",
        highlight = {undercurl = true, sp = "green"},
        auto_close = false,  -- whether or not close this group if it doesn't contain the current buffer
        matcher = function(buf)
          return buf.filename:match('%.md') or buf.filename:match('%.txt')
        end,
        separator = { -- Optional
          style = require('bufferline.groups').separator.tab
        },
      }
    }
  }
```
The matcher line should be changed to move away from buf.filename to using buf.path.

**Comment by akinsho** [comment]
Forgot about this but don't think it's still an issue
