### ISSUE TITLE
Invalid highlight name : Comment 

### ISSUE THREAD

**Issue by siduck76** [akinsho/nvim-bufferline.lua#77]
Hi there , bufferline was working fine for me before but updating it today got me this error 

![image](https://user-images.githubusercontent.com/59060246/113864424-837a0f00-97c8-11eb-9d2b-7b6cb69fc3f1.png)

**Comment by Adnios** [comment]
similar error.
![image](https://user-images.githubusercontent.com/41060790/113865649-e7a7cd80-97de-11eb-8ebf-c88179f0febe.png)

**Comment by drPytho** [comment]
I have the same error, for `Comment` too.

**Comment by akinsho** [comment]
I'll take a look the most recent PR must have a bug. In your case @siduck76 do you have a `Comment` highlight defined?

**Comment by akinsho** [comment]
Ok I just pushed what I'm hoping is a fix. Can people let me know if that resolves the error for them

**Comment by siduck76** [comment]
that resolved the issue thanks!
