### ISSUE TITLE
Buffer switch  have a delay

### ISSUE THREAD

**Issue by glepnir** [akinsho/nvim-bufferline.lua#8]
There will be a significant delay when buffer switching when use `leader number`. see gif  `leader 1` is slow.. And reduce the space of buffer number with buffer name. I want my colorscheme support nvim-bufferline. need provide all highlightgroup
![test](https://user-images.githubusercontent.com/41671631/89389584-2fe68b80-d738-11ea-8e33-d197ce249970.gif)

**Comment by Akin909** [comment]
@glepnir thanks for trying the plugin out, the leader number bindings just call `buffer <number>`. They aren't slow for me so I suspect calling that command might be slow in your config. Can you try it in the commandline and see if it's slow

Regarding the colour scheme stuff I don't really understand what you mean, but as the README points out some themes won't work

**Comment by glepnir** [comment]
@Akin909  Thanks, maybe I need try to remove old keybinds of buffer.then retry it. About colorscehme. I want to say How can I config my colorscheme `oceanic_material` suppor tnvim-bufferline

**Comment by glepnir** [comment]
This plugin seems like https://github.com/ema2159/centaur-tabs.

**Comment by Akin909** [comment]
Ah that's exactly right, it is inspired by that plugin I saw a screenshot of an Emacs users setup and also inspired by atom. I didn't know what the plugin was called, I'll add it to the README

**Comment by Akin909** [comment]
Regarding the colour scheme I can *maybe* take a look when I have time but there plugin works by darkening the `Normal` highlight group to create the contrast between the tabs and the tabline. If normal is a few other basic groups aren't set then it won't work. I've mentioned which ones in the README

**Comment by Akin909** [comment]
@glepnir I've just tried [oceanic material](https://github.com/hardcoreplayers/oceanic-material) on my machine and it seems to work fine by default. Have you overridden some of the colors in your config? can you try with a minimal vimrc loading just the plugin and the colorscheme and see what you get?

I get
![oceanic material bufferline](https://user-images.githubusercontent.com/22454918/89521407-59a2bf80-d7d7-11ea-9a20-40575fcf9ed4.png)

Still looking into the mapping issue

**Comment by glepnir** [comment]
I am author of oceanic_material. I think i am not override it. i will test it when i have time.

**Comment by Akin909** [comment]
I've managed to fix the `<leader>1` mapping it was because I mistakenly created leader mappings from 1-*10* so `<leader>1` was waiting `timeoutlen` before executing making it slower than the others

**Comment by glepnir** [comment]
@Akin909  Aha thanks for work. I will test it later.

**Comment by glepnir** [comment]
The min init.vim. cant't see any colors..
```vim
set runtimepath+=~/.cache/vim/dein/repos/github.com/Akin909/nvim-bufferline.lua
colorscheme oceanic_material
syntax on
lua require'bufferline'.setup()


```
![image](https://user-images.githubusercontent.com/41671631/89548982-5391fa80-d83a-11ea-82fb-b3ba1b827617.png)

**Comment by Akin909** [comment]
Just tried this and it seems to work.
```vim
call plug#begin(stdpath('data') . '/plugged')

Plug 'Akin909/nvim-bufferline.lua'
Plug 'hardcoreplayers/oceanic-material'
call plug#end()

set termguicolors
set background=dark
colorscheme oceanic_material

lua require'bufferline'.setup()
```
*NOTE:* you need `set termguicolors` for this plugin to work

**Comment by glepnir** [comment]
Question is I can't get this color
![image](https://user-images.githubusercontent.com/41671631/89559092-c48bdf00-d847-11ea-8112-107a66a6f0d5.png)

**Comment by Akin909** [comment]
The color isn't hardcoded into the plugin it comes from the `TabLineSel` highlight group set in the plugin. So it will use whatever has been set there. You can override it if you don't like the color your plugin is using

**Comment by akinsho** [comment]
@glepnir I'm going to close this out since the leader mapping is fixed and there is a solution re. the highlights or at least they are behaving correctly. Lemme know if there's still some issue.
