### ISSUE TITLE
How to deal the confict with lightline?

### ISSUE THREAD

**Issue by fgheng** [akinsho/nvim-bufferline.lua#80]
Hello, If I has plugin `lightline`, the tabline will use lightline's tabline other than nvim-bufferline.lua, how to deal it?

I want to use lightline's status line and nvim-bufferline.lua's tabline/bufferline.

**Comment by akinsho** [comment]
@fgheng lightline tries to take over the tabline by default but there is an option to disable it. Please check the lightline docs I'm not sure what it's called as I don't use it.

**Comment by fgheng** [comment]
Hello, I asked lightline's author, config it by

```
let g:lightline = {
    \ 'enable': {
    \   'tabline': 0
    \ },
    \ }
```
thank you.
