### ISSUE TITLE
Doesn't run on startup, have to re-source init.vim

### ISSUE THREAD

**Issue by rickyelopez** [akinsho/nvim-bufferline.lua#82]
Not very familiar with how Lua plugin calls work. I tried adding the `require` from the help/manual to my init.vim, and I've tried a number of other variations including:
` require("bufferline").setup{}`
and
```
lua << EOF
  require("bufferline").setup{}
EOF
```
but none of them work on startup. They all, however, work when I re-source my init.vim after startup.

I'm sure I'm doing something dumb, just dunno what.

**Comment by akinsho** [comment]
@rickyelopez I'm not near a computer right now so can't help properly a couple of things to cross-check. It's the setup call after you load the plugin? Also do you have light line installed since that overrides the tabline and you'd need to disable that part of lightline

**Comment by akinsho** [comment]
@rickyelopez have you had a chance to see if was related to lightline? or plugin loading order?

**Comment by rickyelopez** [comment]
Hey @akinsho, sorry for the delay! No I don't have lightline installed, and yes I am making the setup call after loading the plugin.

I've got:
```
Plug 'kyazdani42/nvim-web-devicons'
Plug 'akinsho/nvim-bufferline.lua'
```

and then
```
lua << EOF
  require("bufferline").setup{}
EOF
```

Any other ideas?

**Comment by akinsho** [comment]
@rickyelopez can you try with a *minimal* init.vim e.g. `nvim -u minimal.vim` where `minimal.vim` is just

```vim
" Other plug setup, which I forget
Plug 'kyazdani42/nvim-web-devicons'
Plug 'akinsho/nvim-bufferline.lua'

lua << EOF
  require("bufferline").setup{}
EOF
``

**Comment by rickyelopez** [comment]
Yup it works fine when I use a minimal init.vim file, which is really strange. Yes I'm using nightly

**Comment by akinsho** [comment]
@rickyelopez the best next step is to gradually add in plugins one by one to see which if any cause the issue. If it's not a plugin then I suggest commenting out chunks of your config until you find the thing that triggers the bug

**Comment by rickyelopez** [comment]
Found it! I had `let g:airline#extensions#tabline#enabled = 1` set for airline. Thanks for the help!
