### ISSUE TITLE
[Question]how to apply two fonts like you demo?

### ISSUE THREAD

**Issue by Young1783** [akinsho/nvim-bufferline.lua#84]
That looks pretty cool and it is really useful.
Thx a lot~

**Comment by Young1783** [comment]
Oh, I browse you repo and dig into you dotfiles. I find the secret!!!

**Comment by linqingyao** [comment]
Although I checked the author's dot file, I still couldn't find relevant information. Can you tell me what kind of magic this is? Thank you very much!
