### ISSUE TITLE
weird highlights in tabs

### ISSUE THREAD

**Issue by elkowar** [akinsho/nvim-bufferline.lua#85]
I've been trying to figure out how the highlights in the tab bar work fully, but I can't figure out how to deal with the diagnostic-indicator text being a different background and foreground than the rest of the tab,...
![image](https://user-images.githubusercontent.com/5300871/116605277-81225500-a92f-11eb-93a3-d976269379ef.png)

I'd like this to have the same background as the rest of the tab, obviously... Idk if this is a bug or a "I don't get it", but either way, help would be greatly appreciated ^^'

**Comment by akinsho** [comment]
@elkowar this is a new one for me I'm not sure what I'm looking at tbh, can you share the configuration you're using. Have you attempted to change anything? what colorscheme are you using and is your terminal truecolor/are you using `termguicolors`?

**Comment by elkowar** [comment]
https://github.com/elkowar/Desktop-dotfiles/blob/master/files/.config/nvim/fnl/plugins/bufferline.fnl here is my relevant config (it's in fennel, but 🤷🏻 ) i'm using termguicolors and using gruvbox-community/gruvbox

**Comment by akinsho** [comment]
By default the diagnostic highlights use `LspDiagnosticsDefault{Error|Warning|Information}` highlights but if your colorscheme doesn't support those it falls back to `Error`, and `WarningMsg` the background is just adapted from the current highlight of the buffer tab.

Sorry @elkowar I really can't follow fennel. It looks like you are in the middle of customising the colors and just need to find the correct one for the diagnostic background

**Comment by akinsho** [comment]
You probably want to change the background values for
```lua
      diagnostic = {
        guifg = comment_diagnostic_fg,
        guibg = background_color,
      },
      diagnostic_visible = {
        guifg = comment_diagnostic_fg,
        guibg = visible_bg,
      },
      diagnostic_selected = {
        guifg = normal_diagnostic_fg,
        guibg = normal_bg,
        gui = "bold,italic",
      },
      info = {
        guifg = comment_fg,
        guisp = info_fg,
        guibg = background_color,
      },
      info_visible = {
        guifg = comment_fg,
        guibg = visible_bg,
      },
      info_selected = {
        guifg = info_fg,
        guibg = normal_bg,
        gui = "bold,italic",
        guisp = info_fg,
      },
      info_diagnostic = {
        guifg = comment_diagnostic_fg,
        guisp = info_diagnostic_fg,
        guibg = background_color,
      },
      info_diagnostic_visible = {
        guifg = comment_diagnostic_fg,
        guibg = visible_bg,
      },
      info_diagnostic_selected = {
        guifg = info_diagnostic_fg,
        guibg = normal_bg,
        gui = "bold,italic",
        guisp = info_diagnostic_fg,
      },

```

**Comment by elkowar** [comment]
Ahhhh, yea, i was missing the info_diagnostic_selected etc highlights,... might be good to link that bit of code in the readme ^^ Thanks for your help!

**Comment by akinsho** [comment]
Glad you found it 👍🏾 It's actually under `:h bufferline-lua-highlights` in the help docs, maybe I'll point to those up more prominently in the README.

**Comment by elkowar** [comment]
Oh wow, surprised I managed to overlook that,... But yea, mentioning that would be cool! Specifically given that you're already mentioning some of the other fields there, may be good to specifically link to that help page :) Thanks!
