### ISSUE TITLE
Ignore splits

### ISSUE THREAD

**Issue by vinicius507** [akinsho/nvim-bufferline.lua#87]
Is there any way to make bufferline ignore splits? Everytime I open a split it lists on the bufferline. If I do `:q` in the split, it closes the split but the buffer stays open and listed.

**Comment by akinsho** [comment]
Hi @vinicius507,

I'm not sure I understand what you mean. A split is a layout in vim so those won't show in bufferline. it only shows buffers so do you mean that if you open a buffer in a split it shouldn't show in the bufferline? When you describe closing the split with `q` that command closes windows but won't delete a vim buffer.

I think there's maybe a mixture of both the window concept and the buffer concept here. This plugin only really shows buffers and doesn't really do anything with windows except for the maybe soon to be deprecated multiwindow mode. If a buffer is open in a window then that buffer is open if you close the window then that buffer is still open (that's just how vim works) if you want to delete a buffer and a window then you need to use `:bd`.

**Comment by akinsho** [comment]
It's not really possible to ignore splits since a split is just how certain buffers are being viewed, as far as this plugin (and nvim) is concerned those buffers are still open and listed regardless of what windows they are in.

**Comment by vinicius507** [comment]
> It's not really possible to ignore splits since a split is just how certain buffers are being viewed, as far as this plugin (and nvim) is concerned those buffers are still open and listed regardless of what windows they are in.

Thanks. I'll search in the documentation if there is any way to list buffers that are in the same window so I can filter them out. :)
Thanks for the clarification, though.
