### ISSUE TITLE
How I can disable italic text?

### ISSUE THREAD

**Issue by gmr458** [akinsho/nvim-bufferline.lua#91]

**Comment by akinsho** [comment]
@gmr458 if you check `:h bufferline-lua-styling` there is documentation on all the highlight groups you can customise. You need to change the `gui` attribute to `NONE` or whatever else you want there. If you are unfamiliar with highlight groups in vim I recommend reading `:h highlight-gui`

**Comment by gmr458** [comment]
@akinsho Thanks!

**Comment by akinsho** [comment]
Gonna close this out now 👍🏾

**Comment by rod-stuchi** [comment]
I tried, but no help for `:h bufferline-lua-highlights` or `:h bufferline-lua-styling`

**Comment by akinsho** [comment]
@rod-stuchi the `-lua-` bit was removed from the help tags so you can just do `:h bufferline-highlights`. FYI you can tab complete help next time to see whats available e.g. `:h bufferline<TAB>` should autocomplete the options if your stuck on this sort of thing in the future.

**Comment by sillyprizes** [comment]
Reading the above references will go a long way, but for those who just want the answer this is the config to remove all styling for the selected buffer:

```
require("bufferline").setup{
  options = {
  },
  highlights = {
    buffer_selected = {
      gui = "none"
    },
  },
}
```
