### ISSUE TITLE
Offset text highlight

### ISSUE THREAD

**Issue by LuisxSullivaN** [akinsho/nvim-bufferline.lua#92]
Hey! thanks for developing this plugin.

I'm wondering if I could set the highlight of the text in the 'offset' config option to show it in cursive and bold as with the buffer active text. I tried to see the code but looks a bit confusing to me. ¡Thanks in advance!

**Comment by akinsho** [comment]
@LuisxSullivaN to set the offset's highlight you have to pass in a highlight group to use. In your highlight group you need to set the `gui` attribute to include `italic`. Have a read through `:h highlight-gui` to get an understanding how that works in vim

**Comment by LuisxSullivaN** [comment]
Thanks again. As you mentioned, I got it working by creating a new highlight group with `:highlight FileExplorer gui=bold,italic`
![image](https://user-images.githubusercontent.com/29529436/117585081-237fcc80-b0d6-11eb-99dd-07f6f75c26d0.png)

**Comment by siduck76** [comment]
@LuisxSullivaN  which font?

**Comment by LuisxSullivaN** [comment]
@siduck76 it's Victor Mono, you can find it on github
